Locale
MicrosoftDocs/globalization pull request #245
Opened 2023-03-07 14:43 UTC by m-kauppinen

4 Locale articles for review.

2023-03-07 14:44 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/locale/fallback.md](https://github.com/MicrosoftDocs/globalization/blob/dacf528f8bebe62b02e2d5bd183e0b733f09a950/globalization%2Flocale%2Ffallback.md) | 79 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1017dcdd-2eae-4fac-ad7b-9c62102ace83) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/locale.md](https://github.com/MicrosoftDocs/globalization/blob/dacf528f8bebe62b02e2d5bd183e0b733f09a950/globalization%2Flocale%2Flocale.md) | 71 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8a75568-68a6-4531-a1af-0e06b438a2b8) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/other-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/dacf528f8bebe62b02e2d5bd183e0b733f09a950/globalization%2Flocale%2Fother-locale-names.md) | 77 | 100 | 76 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b18ea4f9-8a59-41a7-891d-fb552995d94e) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/standard-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/dacf528f8bebe62b02e2d5bd183e0b733f09a950/globalization%2Flocale%2Fstandard-locale-names.md) | 57 | 79 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe5cfd49-5c85-4bce-b7e1-c57e6e3db8ca) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2023-03-09 19:30 UTC, Keika3 commented on globalization/locale/standard-locale-names.md
> +- The Serbo-Croatian “sh” was replaced by Serbian “sr” and Croatian “hr” in 2008.
As per the official (I think) site, the language code "sh" was deprecated on 2000, not on 2008.
https://loc.gov/standards/iso639-2/php/code_changes_bycode.php?code_ID=513
As per this page, "This code was deprecated in 2000 because there were separate language codes for each individual language represented (Serbian, Croatian, and then Bosnian was added)."
2008 seems to be the year for deprecation of another language codes for Serbian and Croatian
https://loc.gov/standards/iso639-2/php/code_changes_bycode.php?code_ID=390 > Serbian ("scc" was deprecated on 2008)
https://loc.gov/standards/iso639-2/php/code_changes_bycode.php?code_ID=394 > Croatian ("scr" was deprecated)

2023-03-09 20:05 UTC, Keika3 commented on globalization/locale/standard-locale-names.md
> +Region subtags have changed as well. For example, Serbia and Montenegro had the ISO 3166-1 alpha-2 subtag “CS” before it was dissolved in 2006. “CS” was deleted from ISO 3166-2, and the new countries
I thought that the word "dissolve" is somewhat offensive. ChatGPT said "The word "dissolve" can be used to describe the situation where a county no longer exists, for example, if it has been absorbed into another county or if it has been abolished. However, the use of this word may be considered insensitive or inappropriate in certain contexts. "
If the native English speakers think it's OK to use this word, I'm OK. But what do you think about using "ceased to exist" instead?

2023-03-09 21:20 UTC, Keika3 commented on globalization/locale/standard-locale-names.md
> +
Should it be same as the title above "Standard locale **naming**" or use "codes" instead of "names"?
I personally think using "name" is a bit confusing as it sounds like a language name (e.g. Japanese language). But here we mean locale "codes".

2023-03-09 21:26 UTC, Keika3 commented on globalization/locale/other-locale-names.md
> +The POSIX locale format, used on Unix, Linux, and other systems, is defined by [ISO/IEC 15897:2011](https://www.iso.org/standard/50707.html) and uses this format: **[language[_territory][.codeset][@m
It may be good if we add an entry of this "POSIX" on the glossary page (https://learn.microsoft.com/en-us/globalization/reference/glossary, https://review.learn.microsoft.com/en-us/globalization/reference/glossary?branch=startup-staging), and add a link to it.

2023-03-09 21:47 UTC, Keika3 commented on globalization/locale/standard-locale-names.md
> +|[ISO 15924](https://unicode.org/iso15924/iso15924-codes.html) script tag |3 letters. |Recommended: Title Case. |Optional |
Too minor, but only this "3 letters" has the ending period in the "Composition" column.

2023-03-10 18:21 UTC, Keika3 commented on globalization/locale/fallback.md
> +
In [the work item](https://dev.azure.com/bagie/Engineering/_workitems/edit/56148) for this page, Agustin mentions about the **extra layer of geopolitical validation** for "`Language Distance", but it seems it's not mentioned on this page.

2023-03-10 18:22 UTC, Keika3 commented on globalization/locale/fallback.md
>  title: Fallback behaviors
Should the title be same as the headline ("Locale fallback" for this page)? It seems most of the pages have the same title between them. I know that this title is not visible though.

2023-03-10 19:20 UTC, Keika3 commented on globalization/locale/fallback.md
> +
This paragraph contains very basic information. Another MS site contains comprehensive information, and I think it may be good if we add a link (or links).
Some examples, 
https://learn.microsoft.com/en-us/dotnet/core/extensions/localization#culture-fallback-scenarios
https://learn.microsoft.com/en-us/dotnet/core/extensions/resources

2023-03-10 19:23 UTC, jowilco commented on globalization/locale/fallback.md
> +
The problem is that CLDR's language distance is only a proposal. As there is no implementation yet, I don't think that it is worth expanding on detail of features that might or might not be implemented.

2023-03-10 19:24 UTC, jowilco commented on globalization/locale/other-locale-names.md
> +
Yes - we can reuse Microsoft content. We should always rephrase/rewrite content from elsewhere.

2023-03-10 19:26 UTC, Keika3 commented on globalization/locale/other-locale-names.md
> +
Thank you for your information!

2023-03-10 19:48 UTC, jowilco commented on globalization/locale/standard-locale-names.md
> +Region subtags have changed as well. For example, Serbia and Montenegro had the ISO 3166-1 alpha-2 subtag “CS” before it was dissolved in 2006. “CS” was deleted from ISO 3166-2, and the new countries
How about "For example, the country of Serbia and Montenegro was assigned the ISO 3166-1 alpha-2 subtag "CS". In 2006, "CS" was deleted from ISO 3166-1 and ISO 3166-2, and the new countries were assigned the subtags “ME” (Montenegro) and “RS” (Serbia)."

2023-03-10 21:50 UTC, agustd commented on globalization/locale/fallback.md
> +
We should add a general note for fallback telling people to validate fallback assumptions for alignment with their organizational geopolitical policies.

2023-03-10 21:51 UTC, Keika3 commented on globalization/locale/standard-locale-names.md
> +Region subtags have changed as well. For example, Serbia and Montenegro had the ISO 3166-1 alpha-2 subtag “CS” before it was dissolved in 2006. “CS” was deleted from ISO 3166-2, and the new countries
Looks good to me.

2023-03-10 22:00 UTC, Keika3 reviewed
I'm done reviewing the current contents.

2023-03-10 22:11 UTC, agustd requested changes
Completed my review and added a couple of comments.

2023-03-10 23:43 UTC, jowilco commented on globalization/locale/fallback.md
> +
@agustd "telling people to validate fallback assumptions" - I think that you are conflating potentially separate ideas here.
The first is the default fallback behavior for operating systems and APIs. Users don't have direct control over that behavior, and this is the behavior that we are describing in this topic.
The second is programmers being able to override or extend the fallback behavior provided by the APIs that they are using. We don't currently address that in this topic, but we could add a new heading mentioning that the default fallbacks provided by APIs might not be sufficient for organizational need, and programmers might want to override or extend the fallback behavior. However, I feel that this is a "no-brainer" for developers where this is an issue, so doesn't warrant mentioning.

2023-03-11 00:27 UTC, agustd commented on globalization/locale/fallback.md
> +
@jowilco, I see. I like your proposal for "_adding a new heading mentioning that the default fallbacks provided by APIs might not be sufficient for organizational need, and programmers might want to override or extend the fallback behavior.__" More often than not, developers are not aware of things like this.

2023-03-13 08:06 UTC, m-kauppinen commented on globalization/locale/fallback.md
>  title: Fallback behaviors
Yes, the difference is not intentional. Fixed.

2023-03-13 08:19 UTC, m-kauppinen commented on globalization/locale/fallback.md
> +
I added those links. @jowilco The writing tool gives a warning that links in this format may fail in isolated environments. Should I replace them with the format the tool suggests (/dotnet/core/extensions/localization) or leave as is?

2023-03-13 08:31 UTC, m-kauppinen commented on globalization/locale/standard-locale-names.md
> +|[ISO 15924](https://unicode.org/iso15924/iso15924-codes.html) script tag |3 letters. |Recommended: Title Case. |Optional |
Good catch! I added those to the other entries in this column.

2023-03-13 09:32 UTC, m-kauppinen commented on globalization/locale/standard-locale-names.md
> +
I changed it to "codes" in the heading and title.

2023-03-13 09:33 UTC, m-kauppinen commented on globalization/locale/standard-locale-names.md
> +Region subtags have changed as well. For example, Serbia and Montenegro had the ISO 3166-1 alpha-2 subtag “CS” before it was dissolved in 2006. “CS” was deleted from ISO 3166-2, and the new countries
Article edited accordingly.

2023-03-13 09:36 UTC, m-kauppinen commented on globalization/locale/standard-locale-names.md
> +- The Serbo-Croatian “sh” was replaced by Serbian “sr” and Croatian “hr” in 2008.
Changed the year in the article.

2023-03-13 10:06 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/locale/fallback.md](https://github.com/MicrosoftDocs/globalization/blob/9b33fdde243f1a82d1964daac14c5c8c52c2ba5e/globalization%2Flocale%2Ffallback.md) | 78 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eed8ad13-2bf6-4af1-b6c7-67e71cff0cc2) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/locale.md](https://github.com/MicrosoftDocs/globalization/blob/9b33fdde243f1a82d1964daac14c5c8c52c2ba5e/globalization%2Flocale%2Flocale.md) | 71 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1a3990e-823d-44e0-8e79-95a104834613) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/other-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/9b33fdde243f1a82d1964daac14c5c8c52c2ba5e/globalization%2Flocale%2Fother-locale-names.md) | 77 | 100 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4ebc317-6624-44c3-acf8-25d240f5de8b) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/standard-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/9b33fdde243f1a82d1964daac14c5c8c52c2ba5e/globalization%2Flocale%2Fstandard-locale-names.md) | 57 | 79 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4e54274-4bd1-4de0-aa1f-0391edac3933) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/glossary.md](https://github.com/MicrosoftDocs/globalization/blob/9b33fdde243f1a82d1964daac14c5c8c52c2ba5e/globalization%2Freference%2Fglossary.md) | 92 | 89 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f066a430-c1ea-4aa4-93e9-0d5fc31a59d1) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2023-03-13 10:23 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/locale/fallback.md](https://github.com/MicrosoftDocs/globalization/blob/4d27ada70e91116d0d71a8cc4bcd1e1226ac7670/globalization%2Flocale%2Ffallback.md) | 78 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1372b1a1-f99a-45ae-bd7c-4a430565f690) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/locale.md](https://github.com/MicrosoftDocs/globalization/blob/4d27ada70e91116d0d71a8cc4bcd1e1226ac7670/globalization%2Flocale%2Flocale.md) | 71 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37ac9a6e-6600-49db-bdfb-ea427d35088e) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/other-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/4d27ada70e91116d0d71a8cc4bcd1e1226ac7670/globalization%2Flocale%2Fother-locale-names.md) | 77 | 100 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef659de7-b9a3-40db-8590-2f880e9e362c) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/standard-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/4d27ada70e91116d0d71a8cc4bcd1e1226ac7670/globalization%2Flocale%2Fstandard-locale-names.md) | 57 | 79 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb499d56-fc85-45f8-b12e-b0d6168c55f5) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/glossary.md](https://github.com/MicrosoftDocs/globalization/blob/4d27ada70e91116d0d71a8cc4bcd1e1226ac7670/globalization%2Freference%2Fglossary.md) | 92 | 89 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5175e29d-47d0-4cba-8931-b5b5fd44b008) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2023-03-13 14:03 UTC, jowilco commented on globalization/locale/fallback.md
> +
Works for me. @agustd ?

2023-03-13 14:04 UTC, jowilco commented on globalization/locale/fallback.md
> +
Please use the recommended format, not that this doc set should ever be used in those environments.

2023-03-13 17:21 UTC, agustd submitted a review, later dismissed

2023-03-13 18:11 UTC, Keika3 commented on globalization/locale/standard-locale-names.md
> +
If we are changing the word from "name" to "code", should we make the change in the following which is the search results of "locale names"?
\GitHub\globalization\globalization\locale\other-locale-names.md (4 hits) 
Line 14: Windows APIs have used BCP 47 locale names since Windows Vista. There are other locale representations, however; some of which are discussed below. 
Line 18: Before Windows adopted IETF BCP 47 locale names, the [[MS-LCID]: Windows Language Code Identifier (LCID) Reference](/openspecs/windows_protocols/ms-lcid/70feba9f-294e-491e-b6eb-56532684c37f) was used to specify locales for Windows. LCIDs are also known as culture identifiers in the Microsoft .NET Framework environment. 
Line 20: Note that LCIDs are being deprecated, and implementers are strongly encouraged to use newer versions of APIs that support BCP 47 locale names instead. Each LCID can be represented by a BCP 47 locale name, but the reverse is not true. The LCID range is restricted and unable to uniquely identify all the possible combinations of language and region. 

  \GitHub\globalization\globalization\locale\standard-locale-names.md (1 hit) 
Line  3: description: This article describes the standard structure of locale names.

2023-03-13 18:35 UTC, Keika3 commented on globalization/locale/other-locale-names.md
> +The POSIX locale format, used on Unix, Linux, and other systems, is defined by [ISO/IEC 15897:2011](https://www.iso.org/standard/50707.html) and uses this format: **[language[_territory][.codeset][@m
Looks good to me, but should we add info on the acronym "POSIX"?

2023-03-14 07:01 UTC, m-kauppinen commented on globalization/locale/other-locale-names.md
> +The POSIX locale format, used on Unix, Linux, and other systems, is defined by [ISO/IEC 15897:2011](https://www.iso.org/standard/50707.html) and uses this format: **[language[_territory][.codeset][@m
It's in the heading on the Glossary page: https://review.learn.microsoft.com/en-us/globalization/reference/glossary?branch=locale

2023-03-14 07:21 UTC, m-kauppinen commented on globalization/locale/standard-locale-names.md
> +
Yeah, it's good to be consistent. I also updated the link list in the Locale article.

2023-03-14 08:20 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/locale/fallback.md](https://github.com/MicrosoftDocs/globalization/blob/51b1f85e2f06c9ff950c6a8d32503b59234189f1/globalization%2Flocale%2Ffallback.md) | 78 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da46a42c-5eed-4b18-8b73-ce001c1feede) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/locale.md](https://github.com/MicrosoftDocs/globalization/blob/51b1f85e2f06c9ff950c6a8d32503b59234189f1/globalization%2Flocale%2Flocale.md) | 71 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/778f55de-86a0-47a3-bf95-b4c3ba60bc01) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/other-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/51b1f85e2f06c9ff950c6a8d32503b59234189f1/globalization%2Flocale%2Fother-locale-names.md) | 77 | 100 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b75c2c16-f00f-496c-ae97-42cffc81efe0) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/standard-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/51b1f85e2f06c9ff950c6a8d32503b59234189f1/globalization%2Flocale%2Fstandard-locale-names.md) | 57 | 79 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd0c095f-5cf1-4e00-a7a8-1e137bfdbf9b) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/glossary.md](https://github.com/MicrosoftDocs/globalization/blob/51b1f85e2f06c9ff950c6a8d32503b59234189f1/globalization%2Freference%2Fglossary.md) | 92 | 89 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f92bdfe-ed7e-4dd3-8782-2dcf4e056e06) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2023-03-15 08:24 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/locale/fallback.md](https://github.com/MicrosoftDocs/globalization/blob/b096ab108225dad2d81a9fe207707ad9ec081fa4/globalization%2Flocale%2Ffallback.md) | 78 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2cf383a-78aa-4c16-aad3-9adebb536ed5) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/locale.md](https://github.com/MicrosoftDocs/globalization/blob/b096ab108225dad2d81a9fe207707ad9ec081fa4/globalization%2Flocale%2Flocale.md) | 71 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d2a9ecb-ca22-480a-acb5-03ace7dc50ed) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/other-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/b096ab108225dad2d81a9fe207707ad9ec081fa4/globalization%2Flocale%2Fother-locale-names.md) | 77 | 100 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d16a1721-84b6-4fc2-8efb-6dd2f2ac4105) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/standard-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/b096ab108225dad2d81a9fe207707ad9ec081fa4/globalization%2Flocale%2Fstandard-locale-names.md) | 57 | 79 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3832bdd-b763-431b-b154-654c1f0b5799) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/glossary.md](https://github.com/MicrosoftDocs/globalization/blob/b096ab108225dad2d81a9fe207707ad9ec081fa4/globalization%2Freference%2Fglossary.md) | 92 | 89 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97caaab3-51c4-4a95-b6ea-338afe942eb3) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2023-03-15 08:39 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/locale/fallback.md](https://github.com/MicrosoftDocs/globalization/blob/1f25beb1265a31759369f988697083073db76232/globalization%2Flocale%2Ffallback.md) | 78 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78783af6-ebd7-4491-b5b8-440abd1464e7) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/locale.md](https://github.com/MicrosoftDocs/globalization/blob/1f25beb1265a31759369f988697083073db76232/globalization%2Flocale%2Flocale.md) | 71 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2a4ee8f-ec31-421d-af76-743f9b120548) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/other-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/1f25beb1265a31759369f988697083073db76232/globalization%2Flocale%2Fother-locale-names.md) | 77 | 100 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8c79203-cf79-4e54-a2c3-01d1a7044e92) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/standard-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/1f25beb1265a31759369f988697083073db76232/globalization%2Flocale%2Fstandard-locale-names.md) | 57 | 79 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e9c3dc8-d016-40b0-9674-ff3118964d4d) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/glossary.md](https://github.com/MicrosoftDocs/globalization/blob/1f25beb1265a31759369f988697083073db76232/globalization%2Freference%2Fglossary.md) | 92 | 89 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb1f76d0-f502-424c-bfee-9749a98af149) | [:white_check_mark:](# "Successfully processed") |
| [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/1f25beb1265a31759369f988697083073db76232/globalization%2Ftoc.yml) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc2e2a9d-f7ad-4db4-87ca-ea11c205eb23) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2023-03-15 15:51 UTC, jowilco approved these changes

2023-03-15 15:56 UTC, agustd approved these changes

2023-03-16 09:19 UTC, merged