56178 56187 text and text layout
MicrosoftDocs/globalization pull request #279
Opened 2023-10-31 22:55 UTC by jowilco

2023-10-31 22:55 UTC, acrolinx-at-msft2 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/fonts-layout/displaying-text.md](https://github.com/MicrosoftDocs/globalization/blob/ffd2b13fd37ccef41a0c9eee608c6406967bdbc0/globalization%2Ffonts-layout%2Fdisplaying-text.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26eb6cb3-4344-4ba6-9289-ee4287c59730) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/emoji.md](https://github.com/MicrosoftDocs/globalization/blob/ffd2b13fd37ccef41a0c9eee608c6406967bdbc0/globalization%2Ffonts-layout%2Femoji.md) | 85 | 100 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73a0efee-331e-4145-84eb-328ed84b0b3b) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/font-support.md](https://github.com/MicrosoftDocs/globalization/blob/ffd2b13fd37ccef41a0c9eee608c6406967bdbc0/globalization%2Ffonts-layout%2Ffont-support.md) | 78 | 100 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94ee73b7-2562-403c-97b3-63a8ed940379) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/fonts.md](https://github.com/MicrosoftDocs/globalization/blob/ffd2b13fd37ccef41a0c9eee608c6406967bdbc0/globalization%2Ffonts-layout%2Ffonts.md) | 88 | 100 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aada8439-3409-475e-b8f5-351300696d10) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/line-and-word-breaking.md](https://github.com/MicrosoftDocs/globalization/blob/ffd2b13fd37ccef41a0c9eee608c6406967bdbc0/globalization%2Ffonts-layout%2Fline-and-word-breaking.md) | 73 | 100 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a69be653-749a-4875-8fc2-f011c312c295) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/multi-script-fonts.md](https://github.com/MicrosoftDocs/globalization/blob/ffd2b13fd37ccef41a0c9eee608c6406967bdbc0/globalization%2Ffonts-layout%2Fmulti-script-fonts.md) | 95 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96572785-75c5-4f77-881a-e2e9d8173424) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/pagination.md](https://github.com/MicrosoftDocs/globalization/blob/ffd2b13fd37ccef41a0c9eee608c6406967bdbc0/globalization%2Ffonts-layout%2Fpagination.md) | 71 | 77 | 83 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b75b83e-9085-4add-bfbc-a8ea9cc506eb) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/ruby.md](https://github.com/MicrosoftDocs/globalization/blob/ffd2b13fd37ccef41a0c9eee608c6406967bdbc0/globalization%2Ffonts-layout%2Fruby.md) | 70 | 80 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67e4b5d1-a57b-4e18-abfb-29617d6fcabc) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-boundaries.md](https://github.com/MicrosoftDocs/globalization/blob/ffd2b13fd37ccef41a0c9eee608c6406967bdbc0/globalization%2Ffonts-layout%2Ftext-boundaries.md) | 69 | 88 | 65 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9fd80f93-4c15-40c1-b396-a078b0d85e4f) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-directionality.md](https://github.com/MicrosoftDocs/globalization/blob/ffd2b13fd37ccef41a0c9eee608c6406967bdbc0/globalization%2Ffonts-layout%2Ftext-directionality.md) | 70 | 91 | 65 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/204c5e27-3e80-4a14-890f-399d993b1c24) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-justification.md](https://github.com/MicrosoftDocs/globalization/blob/ffd2b13fd37ccef41a0c9eee608c6406967bdbc0/globalization%2Ffonts-layout%2Ftext-justification.md) | 74 | 100 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/754e7db2-42ea-49b3-b54f-e42ca74639b6) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-layout.md](https://github.com/MicrosoftDocs/globalization/blob/ffd2b13fd37ccef41a0c9eee608c6406967bdbc0/globalization%2Ffonts-layout%2Ftext-layout.md) | 67 | 83 | 58 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fb8a5b5-91e9-427c-b2f2-cef91e2c5dc0) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/writing-systems.md](https://github.com/MicrosoftDocs/globalization/blob/ffd2b13fd37ccef41a0c9eee608c6406967bdbc0/globalization%2Ffonts-layout%2Fwriting-systems.md) | 85 | 100 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/719e5237-83e4-4871-ac1e-27afa1f506c2) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/opentype.md](https://github.com/MicrosoftDocs/globalization/blob/ffd2b13fd37ccef41a0c9eee608c6406967bdbc0/globalization%2Freference%2Fopentype.md) | 89 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a8d3faa-4c00-4eb9-a0ff-bced14561d3f) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/universal-shaping-engine.md](https://github.com/MicrosoftDocs/globalization/blob/ffd2b13fd37ccef41a0c9eee608c6406967bdbc0/globalization%2Freference%2Funiversal-shaping-engine.md) | 89 | 100 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff7c6147-bb1f-43e8-bb7d-083797afc49d) | [:white_check_mark:](# "Successfully processed") |
| [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/ffd2b13fd37ccef41a0c9eee608c6406967bdbc0/globalization%2Ftoc.yml) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ce30c54-b06a-4931-8448-c4f2f15e1b22) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2023-10-31 22:56 UTC, brunolewin-msft commented
[like]  Bruno Lewin (Centific Technolo... reacted to your message:
________________________________
From: John Wilcock ***@***.***>
Sent: Tuesday, October 31, 2023 10:55:14 PM
To: MicrosoftDocs/globalization ***@***.***>
Cc: Bruno Lewin (Centific Technologies Inc) ***@***.***>; Review requested ***@***.***>
Subject: [MicrosoftDocs/globalization] 56178 56187 text and text layout (PR #279)

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/MicrosoftDocs/globalization/pull/279

Commit Summary

  *   78db7be<https://github.com/MicrosoftDocs/globalization/pull/279/commits/78db7be04d1a6cb944961ac37f6d699d0f2f91d9> Initial checkin
  *   a029dac<https://github.com/MicrosoftDocs/globalization/pull/279/commits/a029dacc20206fa85d49f97d21de4bb350be9b52> Fixed build errors
  *   ffd2b13<https://github.com/MicrosoftDocs/globalization/pull/279/commits/ffd2b13fd37ccef41a0c9eee608c6406967bdbc0> More cleanup

File Changes

(31 files<https://github.com/MicrosoftDocs/globalization/pull/279/files>)

  *   A globalization/fonts-layout/UDHR_he.html<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-28a30a9bb0553194eb962dd53e0b1ab8f93a1eb154a67d69277b43cede3f3095> (36)
  *   A globalization/fonts-layout/UDHR_horizontal.html<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-bc1e34b260c8db593c9411cc5c76823eebe605cbbd16bd9696295e7a03ec3472> (47)
  *   A globalization/fonts-layout/UDHR_mn-Mong.html<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-cdb71a23ebe8f672e2883fe64e035c5be0587c08944d0caca0a4ab5d95020786> (37)
  *   A globalization/fonts-layout/UDHR_vertical.html<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-d68db90f86831c96fd4e346c4e45a73f1b8ae549daa99304359326c63159c936> (47)
  *   A globalization/fonts-layout/UDHR_zh-Hant.html<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-5c94136b0deb93d1e632975501629aeb8dda7fdf8ea5cc3f622d7ca94e7d2b43> (36)
  *   D globalization/fonts-layout/bidirectional-text.md<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-faa8c003a308473bd2a29cba322352abce7e6277531e1a75536eb02bf4628200> (7)
  *   A globalization/fonts-layout/displaying-text.md<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-2ecbf187e4d4f54847224b6f27a6276d33b551fed644e545ce10d3475e2601a5> (29)
  *   M globalization/fonts-layout/emoji.md<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-50592bf4b95f0f35a738d95c6c1f6acb9b6b05d138c07d89ba3bb8ac40a990bf> (28)
  *   A globalization/fonts-layout/font-support.md<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-49ad0e2cb0c40d5df19a857ef4deecfeeef17ffa6d795be6bd8323b797382a65> (461)
  *   M globalization/fonts-layout/fonts.md<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-7a39cdb82a628ed3c3ed14d3cb9e7c5d4c496ac2bd074e778fcf77effa92e569> (69)
  *   A globalization/fonts-layout/images/Cursor_Pos.png<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-8abbf4e4b010200157dd0515f4c3239f0a0eed0d85fd40ab2bd9f95fde577866> (0)
  *   A globalization/fonts-layout/images/Right-Arrow.png<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-24d6eb9110e1c5f2353da427fdd0512efa99bca98202fa7eb2286c7b42d1d0dd> (0)
  *   A globalization/fonts-layout/images/logical_order.png<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-3d24ca930af6825917294b17292049f366d013b9bd214f3d5d28d140d516132d> (0)
  *   A globalization/fonts-layout/images/visual_order.png<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-abcf8d41c54cdc21cf274604fcab9c4dc8e54f5df3036ac218156016d13a2817> (0)
  *   A globalization/fonts-layout/images/weak_character_directionality.png<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-cf2e3cb79e7f02fdc1f50f929f9c08ee22c14bffafd262d21797a1cfebc83934> (0)
  *   A globalization/fonts-layout/images/windows-logo-key.png<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-e83e41504c0d3d5b214a070de34c195a40311bbbf885f0c67c7ab8c45c420b6a> (0)
  *   A globalization/fonts-layout/line-and-word-breaking.md<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-2071c6889274ed28dbb853d24ef2c27572e28b3cd470f23ffd8c139d86fe2ddb> (49)
  *   M globalization/fonts-layout/multi-script-fonts.md<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-a2ca1467303baea99564853c43c22f765ecdb16520deaf86ba8ed78244dfb1a2> (22)
  *   M globalization/fonts-layout/pagination.md<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-7a8ac6c257a1f8f1080feaad4ac8984ada92533ade7cc6ce7a5c960b200f306b> (68)
  *   M globalization/fonts-layout/ruby.md<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-8ae88264dab9c78b097bf0bf6bffcfc003ada3a61944a7a7d1c441bf77271623> (27)
  *   A globalization/fonts-layout/ruby_horizontal.html<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-1038706393f1b5c2ed9ef6c0ef7217d31a610e9c4263d42e4d6320db4325e416> (41)
  *   A globalization/fonts-layout/ruby_vertical.html<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-29591a7110bfe894129a8cb8a3a51e5c0d1d5a2c9e9f6f52c281dc91b2b0bdc8> (41)
  *   M globalization/fonts-layout/text-boundaries.md<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-7b5e2e8e937a72295764d7d88729c935f164189f68a4794917e900971d559e46> (36)
  *   A globalization/fonts-layout/text-directionality.md<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-53a69952fd703b05e344d4d098fd526346652553004f1a3fb7e5ace739cd3c6d> (135)
  *   M globalization/fonts-layout/text-justification.md<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-23adeba3e6d24aad70b01d7c26b9c58abfa054891717b3a63bc9dd0ff437b530> (25)
  *   M globalization/fonts-layout/text-layout.md<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-096df95235ef253bd7514a64601df0405f37e5ac7df1788a1701f8e940b01b96> (54)
  *   A globalization/fonts-layout/writing-systems.md<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-c999d6c7a12f38ff4aadc9b8cb43cc584173ed10a580bcfa97c945aa122be77a> (62)
  *   D globalization/input/line-and-word-breaking.md<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-f326d6fadea56b2c2758823c816a638216d194b8b4d43a589c06c1f13b2ba270> (13)
  *   M globalization/reference/opentype.md<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-6f083c737c6ae9f8ab386963962db15e1b5c1ded081004c157477821b2f9f86c> (31)
  *   M globalization/reference/universal-shaping-engine.md<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-00baf205928b7783f22129debdf96acc50fcea66b19aebb9cf4630d658deb675> (29)
  *   M globalization/toc.yml<https://github.com/MicrosoftDocs/globalization/pull/279/files#diff-ba78fd366171a43cc6a9ab69d4d1e039aaac81507d29e0b00c480934815db1e8> (20)

Patch Links:

  *   https://github.com/MicrosoftDocs/globalization/pull/279.patch
  *   https://github.com/MicrosoftDocs/globalization/pull/279.diff

—
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/globalization/pull/279>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AEKVIQH4ZQODMVVMNER7EXTYCF6VFAVCNFSM6AAAAAA6YOGVQSVHI2DSMVQWIX3LMV43ASLTON2WKOZRHE3TCNBQHEZTOMI>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2023-10-31 22:58 UTC, acrolinx-at-msft2 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/fonts-layout/displaying-text.md](https://github.com/MicrosoftDocs/globalization/blob/27d25912d2d1b466a4e27bf78f00e0b28325d835/globalization%2Ffonts-layout%2Fdisplaying-text.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1912a878-4d98-4fec-a6b0-76c5ec36a7a7) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/emoji.md](https://github.com/MicrosoftDocs/globalization/blob/27d25912d2d1b466a4e27bf78f00e0b28325d835/globalization%2Ffonts-layout%2Femoji.md) | 85 | 100 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3367569-569b-4abe-9bfb-688b00e1daae) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/font-support.md](https://github.com/MicrosoftDocs/globalization/blob/27d25912d2d1b466a4e27bf78f00e0b28325d835/globalization%2Ffonts-layout%2Ffont-support.md) | 78 | 100 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36dc0bec-56e7-4c71-9123-90feaf4e3b8a) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/fonts.md](https://github.com/MicrosoftDocs/globalization/blob/27d25912d2d1b466a4e27bf78f00e0b28325d835/globalization%2Ffonts-layout%2Ffonts.md) | 88 | 100 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9989eb90-99b3-4770-a445-a556e70589e4) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/line-and-word-breaking.md](https://github.com/MicrosoftDocs/globalization/blob/27d25912d2d1b466a4e27bf78f00e0b28325d835/globalization%2Ffonts-layout%2Fline-and-word-breaking.md) | 73 | 100 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ff55fe2-3f9e-4116-adee-2d991b573916) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/multi-script-fonts.md](https://github.com/MicrosoftDocs/globalization/blob/27d25912d2d1b466a4e27bf78f00e0b28325d835/globalization%2Ffonts-layout%2Fmulti-script-fonts.md) | 95 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96718996-a0fe-4512-949c-d5cb537fdd03) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/pagination.md](https://github.com/MicrosoftDocs/globalization/blob/27d25912d2d1b466a4e27bf78f00e0b28325d835/globalization%2Ffonts-layout%2Fpagination.md) | 71 | 77 | 83 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/871fd5ea-0dff-4a31-84e1-6707802fa101) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/ruby.md](https://github.com/MicrosoftDocs/globalization/blob/27d25912d2d1b466a4e27bf78f00e0b28325d835/globalization%2Ffonts-layout%2Fruby.md) | 70 | 80 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d97b7b1f-aa4e-4bc9-9152-5efd86c763aa) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-boundaries.md](https://github.com/MicrosoftDocs/globalization/blob/27d25912d2d1b466a4e27bf78f00e0b28325d835/globalization%2Ffonts-layout%2Ftext-boundaries.md) | 69 | 88 | 65 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bead7873-2994-428d-bb35-2b0e5a08d297) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-directionality.md](https://github.com/MicrosoftDocs/globalization/blob/27d25912d2d1b466a4e27bf78f00e0b28325d835/globalization%2Ffonts-layout%2Ftext-directionality.md) | 70 | 91 | 65 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/116c71de-a4c5-4619-b086-9845f55b1e9c) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-justification.md](https://github.com/MicrosoftDocs/globalization/blob/27d25912d2d1b466a4e27bf78f00e0b28325d835/globalization%2Ffonts-layout%2Ftext-justification.md) | 74 | 100 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c87d3e1-f34a-4e0e-99b9-0d87667bf8d1) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-layout.md](https://github.com/MicrosoftDocs/globalization/blob/27d25912d2d1b466a4e27bf78f00e0b28325d835/globalization%2Ffonts-layout%2Ftext-layout.md) | 67 | 83 | 58 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/466f5948-39fe-416d-9b69-d96ec3ac62c2) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/writing-systems.md](https://github.com/MicrosoftDocs/globalization/blob/27d25912d2d1b466a4e27bf78f00e0b28325d835/globalization%2Ffonts-layout%2Fwriting-systems.md) | 85 | 100 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73a8235c-75cb-40e0-9b66-75a008dce9ee) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/opentype.md](https://github.com/MicrosoftDocs/globalization/blob/27d25912d2d1b466a4e27bf78f00e0b28325d835/globalization%2Freference%2Fopentype.md) | 89 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c7851c4-8907-469a-9d15-e50489d0ff24) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/universal-shaping-engine.md](https://github.com/MicrosoftDocs/globalization/blob/27d25912d2d1b466a4e27bf78f00e0b28325d835/globalization%2Freference%2Funiversal-shaping-engine.md) | 89 | 100 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5d6a586-5d87-4633-bf8e-802f8beb31d1) | [:white_check_mark:](# "Successfully processed") |
| [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/27d25912d2d1b466a4e27bf78f00e0b28325d835/globalization%2Ftoc.yml) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73da12bf-b33f-45fc-bc9e-20fed9e39bb5) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2023-11-01 00:17 UTC, brunolewin-msft commented on globalization/fonts-layout/text-directionality.md
> +Writing systems like Arabic and Hebrew use both LTR and RTL directionality depending on the characters. Basic letters flow from right-to-left, but digits especially when written using [Latin numbers]
**Minor**: a bit of inconsistency in hyphenation and capitalization throughout the PR for "Left-to-Right", "left-to-right", "left to right", "LTR" (and same for RTL, TTB, BTT).

2023-11-01 17:30 UTC, brunolewin-msft commented on globalization/fonts-layout/emoji.md
> +To display glyphs in defined in the Unicode standard in your UI, the font that you use needs to support the glyphs that you're using. Similarly, to display emoji, the device, browser, or font used mu
```suggestion
To display glyphs defined in the Unicode standard in your UI, the font that you use needs to support the glyphs that you're using. Similarly, to display emoji, the device, browser, or font used must be able to represent the emoji.
```

2023-11-01 17:38 UTC, brunolewin-msft commented on globalization/fonts-layout/pagination.md
> +Type alignment sometimes referred to as “text alignment”, “text justification”, “type justification”, or “document direction.” Additionally, this may be referred to as "reading order"; reading order
```suggestion
Type alignment is sometimes referred to as “text alignment”, “text justification”, “type justification”, or “document direction.” Additionally, this may be referred to as "reading order"; reading order describes the order in which a block of text is displayed, sometimes in contrast with how the text is entered or stored, which is normally in logical order.
```

2023-11-01 17:53 UTC, brunolewin-msft commented on globalization/fonts-layout/pagination.md
> +For more information about CSS Writing Modes Level 3, see https://www.w3.org/TR/css-writing-modes-3/
This section sounds like CSS is the main way of controlling directionality, while the linked reference https://www.w3.org/TR/css-writing-modes-3 suggests _avoiding using CSS_ in key cases. Not 100% sure what is right here, but if you do, might be interesting to call out and resolve the apparent contradiction (I've seen the CSS be very helpful, esp. around making the loc process more resilient, so maybe that could be an aspect)

2023-11-01 22:54 UTC, brunolewin-msft commented on globalization/fonts-layout/fonts.md
> +Applications should endeavor to display glyphs correctly, irrespective of the script used. Displaying the correct glyph involves techniques like font fallback. For Windows, several text layout and gl
Suggestion: maybe add something along the lines of: In most cases, developers won't need to use these technologies [../..] **but should follow the _font guidelines_ below**.

2023-11-01 23:03 UTC, brunolewin-msft commented on globalization/toc.yml
>        - name: Justification
```suggestion
      - name: Text Justification
```

2023-11-01 23:07 UTC, brunolewin-msft submitted a review, later dismissed
Added a few suggestions around style/clarity - no blocking issues.

2023-11-02 17:51 UTC, agustd requested changes

2023-11-02 17:51 UTC, agustd commented on globalization/fonts-layout/font-support.md
> +# Script and font support in Windows
Would it be possible to add jump links to each of the releases for easier navigation?

2023-11-02 17:51 UTC, agustd commented on globalization/fonts-layout/fonts.md
> +## Font fallback
Perhaps it'd be worth describing the concept of "document fonts", i.e., fonts embedded in the document to ensure that they display in operating systems that don't support them.

2023-11-10 18:01 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/fonts-layout/displaying-text.md](https://github.com/MicrosoftDocs/globalization/blob/f36e5c9c3f95411e9bf70079ec1320740edc41a5/globalization%2Ffonts-layout%2Fdisplaying-text.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/76e3d510-392e-4a74-89fc-6220e230ffca) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/emoji.md](https://github.com/MicrosoftDocs/globalization/blob/f36e5c9c3f95411e9bf70079ec1320740edc41a5/globalization%2Ffonts-layout%2Femoji.md) | 85 | 100 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c22b972-c2dd-419f-aab6-3f99ff39cbf4) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/font-support.md](https://github.com/MicrosoftDocs/globalization/blob/f36e5c9c3f95411e9bf70079ec1320740edc41a5/globalization%2Ffonts-layout%2Ffont-support.md) | 79 | 100 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bef8eb7-374a-4bab-8d9b-1118ba0c10cf) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/fonts.md](https://github.com/MicrosoftDocs/globalization/blob/f36e5c9c3f95411e9bf70079ec1320740edc41a5/globalization%2Ffonts-layout%2Ffonts.md) | 88 | 100 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18a67448-fa33-4100-afe5-78b231f92348) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/line-and-word-breaking.md](https://github.com/MicrosoftDocs/globalization/blob/f36e5c9c3f95411e9bf70079ec1320740edc41a5/globalization%2Ffonts-layout%2Fline-and-word-breaking.md) | 93 | 100 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/146497fa-cb55-4494-bcc1-0e6f723f54de) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/multi-script-fonts.md](https://github.com/MicrosoftDocs/globalization/blob/f36e5c9c3f95411e9bf70079ec1320740edc41a5/globalization%2Ffonts-layout%2Fmulti-script-fonts.md) | 95 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e63b531c-5015-4ebd-a0fa-d4c86e047785) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/pagination.md](https://github.com/MicrosoftDocs/globalization/blob/f36e5c9c3f95411e9bf70079ec1320740edc41a5/globalization%2Ffonts-layout%2Fpagination.md) | 77 | 100 | 83 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64ecb661-49fa-4d66-b509-c5ca90d0c846) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/ruby.md](https://github.com/MicrosoftDocs/globalization/blob/f36e5c9c3f95411e9bf70079ec1320740edc41a5/globalization%2Ffonts-layout%2Fruby.md) | 93 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fea40808-aa86-43df-8990-ee5b4810bd66) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-boundaries.md](https://github.com/MicrosoftDocs/globalization/blob/f36e5c9c3f95411e9bf70079ec1320740edc41a5/globalization%2Ffonts-layout%2Ftext-boundaries.md) | 89 | 100 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a29cfef1-9dcb-4ecf-b49e-64538660b38f) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-directionality.md](https://github.com/MicrosoftDocs/globalization/blob/f36e5c9c3f95411e9bf70079ec1320740edc41a5/globalization%2Ffonts-layout%2Ftext-directionality.md) | 81 | 100 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82e2f300-601f-4fe1-8b0f-3449148bed5f) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-justification.md](https://github.com/MicrosoftDocs/globalization/blob/f36e5c9c3f95411e9bf70079ec1320740edc41a5/globalization%2Ffonts-layout%2Ftext-justification.md) | 97 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d244f988-c3ea-481c-8cda-39da4997ac0b) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-layout.md](https://github.com/MicrosoftDocs/globalization/blob/f36e5c9c3f95411e9bf70079ec1320740edc41a5/globalization%2Ffonts-layout%2Ftext-layout.md) | 84 | 100 | 70 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/448aaddc-8bf6-401d-928d-e63e3540a4a0) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/writing-systems.md](https://github.com/MicrosoftDocs/globalization/blob/f36e5c9c3f95411e9bf70079ec1320740edc41a5/globalization%2Ffonts-layout%2Fwriting-systems.md) | 85 | 100 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5cf3d6c-f7c3-4c16-9540-0e9594ef0e84) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/opentype.md](https://github.com/MicrosoftDocs/globalization/blob/f36e5c9c3f95411e9bf70079ec1320740edc41a5/globalization%2Freference%2Fopentype.md) | 89 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b20a6706-541a-44c3-9024-e601a4fae776) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/universal-shaping-engine.md](https://github.com/MicrosoftDocs/globalization/blob/f36e5c9c3f95411e9bf70079ec1320740edc41a5/globalization%2Freference%2Funiversal-shaping-engine.md) | 89 | 100 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d41ac46-c7d0-42ce-8710-317c14c65add) | [:white_check_mark:](# "Successfully processed") |
| [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/f36e5c9c3f95411e9bf70079ec1320740edc41a5/globalization%2Ftoc.yml) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d635893-eb55-4b71-a53b-5421b41f8c33) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2023-11-10 18:06 UTC, jowilco commented on globalization/fonts-layout/font-support.md
> +# Script and font support in Windows
Are you only looking at the Markdown? The build system adds links to headings in the generated HTML:
![image](https://github.com/MicrosoftDocs/globalization/assets/16766027/3763bbee-1e18-47dd-aa31-38c0abc59d0a)

2023-11-10 18:34 UTC, jowilco commented on globalization/fonts-layout/pagination.md
> +For more information about CSS Writing Modes Level 3, see https://www.w3.org/TR/css-writing-modes-3/
@brunolewin-msft Just to clarify, are you saying that CSS is saying to avoid using writing-mode, or avoid using rotate + transform?
I think this depends on the use case. I would have thought that in most cases, writing-mode is the correct approach, especially for larger chunks of block text; however, for small amounts of text for which you want to apply style for artistic purposes, you might want to customize the behavior using rotate and transform.

2023-11-10 18:40 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/fonts-layout/displaying-text.md](https://github.com/MicrosoftDocs/globalization/blob/d606218adaab13e3f10146411f41c9caf84fa865/globalization%2Ffonts-layout%2Fdisplaying-text.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab0ef6c4-9d76-4e45-b70d-b5ee8cca94ba) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/emoji.md](https://github.com/MicrosoftDocs/globalization/blob/d606218adaab13e3f10146411f41c9caf84fa865/globalization%2Ffonts-layout%2Femoji.md) | 86 | 100 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/810d7fa6-2451-4b99-be7a-813c54875fb0) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/font-support.md](https://github.com/MicrosoftDocs/globalization/blob/d606218adaab13e3f10146411f41c9caf84fa865/globalization%2Ffonts-layout%2Ffont-support.md) | 79 | 100 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/123970f6-d5cb-4652-9dd5-40dc5e54bdf6) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/fonts.md](https://github.com/MicrosoftDocs/globalization/blob/d606218adaab13e3f10146411f41c9caf84fa865/globalization%2Ffonts-layout%2Ffonts.md) | 88 | 100 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/834af853-eaaa-4f4b-9e29-f6092ffe1d9e) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/line-and-word-breaking.md](https://github.com/MicrosoftDocs/globalization/blob/d606218adaab13e3f10146411f41c9caf84fa865/globalization%2Ffonts-layout%2Fline-and-word-breaking.md) | 93 | 100 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5d3d9f9-47bf-4e52-9c21-8dcf66f51903) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/multi-script-fonts.md](https://github.com/MicrosoftDocs/globalization/blob/d606218adaab13e3f10146411f41c9caf84fa865/globalization%2Ffonts-layout%2Fmulti-script-fonts.md) | 95 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa0a5738-5b12-4db9-ac69-5f6921c0e248) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/pagination.md](https://github.com/MicrosoftDocs/globalization/blob/d606218adaab13e3f10146411f41c9caf84fa865/globalization%2Ffonts-layout%2Fpagination.md) | 77 | 100 | 83 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b26de9da-8d25-45bd-aa40-72756a87872f) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/ruby.md](https://github.com/MicrosoftDocs/globalization/blob/d606218adaab13e3f10146411f41c9caf84fa865/globalization%2Ffonts-layout%2Fruby.md) | 93 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/414f9a98-e953-41bd-b6ef-e7514d18c51d) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-boundaries.md](https://github.com/MicrosoftDocs/globalization/blob/d606218adaab13e3f10146411f41c9caf84fa865/globalization%2Ffonts-layout%2Ftext-boundaries.md) | 89 | 100 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ee64a1a-0528-4777-835b-329abe4db20c) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-directionality.md](https://github.com/MicrosoftDocs/globalization/blob/d606218adaab13e3f10146411f41c9caf84fa865/globalization%2Ffonts-layout%2Ftext-directionality.md) | 81 | 100 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/325d2c4b-f7c5-4a29-bcc9-73545d077c14) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-justification.md](https://github.com/MicrosoftDocs/globalization/blob/d606218adaab13e3f10146411f41c9caf84fa865/globalization%2Ffonts-layout%2Ftext-justification.md) | 97 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a789038-343f-4d7d-9594-462585105bf0) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-layout.md](https://github.com/MicrosoftDocs/globalization/blob/d606218adaab13e3f10146411f41c9caf84fa865/globalization%2Ffonts-layout%2Ftext-layout.md) | 84 | 100 | 70 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3a58b8e-2469-4888-a527-01375a508d5f) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/writing-systems.md](https://github.com/MicrosoftDocs/globalization/blob/d606218adaab13e3f10146411f41c9caf84fa865/globalization%2Ffonts-layout%2Fwriting-systems.md) | 85 | 100 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6ff579e-b180-4c0e-99ed-588bfcbf1154) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/opentype.md](https://github.com/MicrosoftDocs/globalization/blob/d606218adaab13e3f10146411f41c9caf84fa865/globalization%2Freference%2Fopentype.md) | 89 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa472f5c-a592-4518-9cb5-0097ca06a145) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/universal-shaping-engine.md](https://github.com/MicrosoftDocs/globalization/blob/d606218adaab13e3f10146411f41c9caf84fa865/globalization%2Freference%2Funiversal-shaping-engine.md) | 89 | 100 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/327c5688-d032-4262-8b4e-39f8590ab70a) | [:white_check_mark:](# "Successfully processed") |
| [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/d606218adaab13e3f10146411f41c9caf84fa865/globalization%2Ftoc.yml) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53661f46-cc29-4afc-b8f1-c2984518eade) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2023-11-10 18:40 UTC, jowilco commented on globalization/fonts-layout/text-directionality.md
> +Writing systems like Arabic and Hebrew use both LTR and RTL directionality depending on the characters. Basic letters flow from right-to-left, but digits especially when written using [Latin numbers]
I tweaked this a bit. I'm trying to use "left-to-right" when it is either an adjective or as a noun, but "left to right" when I am specifying a direction.

2023-11-10 18:40 UTC, jowilco commented on globalization/fonts-layout/emoji.md
> +To display glyphs in defined in the Unicode standard in your UI, the font that you use needs to support the glyphs that you're using. Similarly, to display emoji, the device, browser, or font used mu
Fixed

2023-11-10 18:40 UTC, jowilco commented on globalization/fonts-layout/pagination.md
> +Type alignment sometimes referred to as “text alignment”, “text justification”, “type justification”, or “document direction.” Additionally, this may be referred to as "reading order"; reading order
Fixed

2023-11-10 18:41 UTC, jowilco commented on globalization/fonts-layout/fonts.md
> +Applications should endeavor to display glyphs correctly, irrespective of the script used. Displaying the correct glyph involves techniques like font fallback. For Windows, several text layout and gl
Fixed

2023-11-10 18:41 UTC, jowilco commented on globalization/toc.yml
>        - name: Justification
Fixed

2023-11-10 18:41 UTC, jowilco commented on globalization/fonts-layout/displaying-text.md
> +User interface text is text that appears on UI surfaces. This text includes control labels and static text:
Added a new bullet.

2023-11-10 18:41 UTC, jowilco commented on globalization/fonts-layout/emoji.md
>  # Emoji
Added a para.

2023-11-10 18:41 UTC, jowilco commented on globalization/fonts-layout/fonts.md
> +## Font fallback
Added a section for font embedding.

2023-11-10 18:45 UTC, agustd submitted a review, later dismissed

2023-11-10 21:19 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/fonts-layout/displaying-text.md](https://github.com/MicrosoftDocs/globalization/blob/fd6bc191ae4483fb0654e4624190a01ac5cbbbd1/globalization%2Ffonts-layout%2Fdisplaying-text.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f35f9ca-a6e9-4754-9134-68fe51189d72) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/emoji.md](https://github.com/MicrosoftDocs/globalization/blob/fd6bc191ae4483fb0654e4624190a01ac5cbbbd1/globalization%2Ffonts-layout%2Femoji.md) | 86 | 100 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d21286ab-45ea-43cb-bd34-947f256e656a) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/font-support.md](https://github.com/MicrosoftDocs/globalization/blob/fd6bc191ae4483fb0654e4624190a01ac5cbbbd1/globalization%2Ffonts-layout%2Ffont-support.md) | 79 | 100 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1871b7c8-0eaf-4e7f-ae4a-188958b296b2) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/fonts.md](https://github.com/MicrosoftDocs/globalization/blob/fd6bc191ae4483fb0654e4624190a01ac5cbbbd1/globalization%2Ffonts-layout%2Ffonts.md) | 88 | 100 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0cdc30e-e99a-4282-84cb-edff5f006b71) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/line-and-word-breaking.md](https://github.com/MicrosoftDocs/globalization/blob/fd6bc191ae4483fb0654e4624190a01ac5cbbbd1/globalization%2Ffonts-layout%2Fline-and-word-breaking.md) | 93 | 100 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d92f3861-41c7-4b93-a8c3-9a73186846cc) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/multi-script-fonts.md](https://github.com/MicrosoftDocs/globalization/blob/fd6bc191ae4483fb0654e4624190a01ac5cbbbd1/globalization%2Ffonts-layout%2Fmulti-script-fonts.md) | 95 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88866bd3-83d2-40dd-92b9-a623344127c3) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/pagination.md](https://github.com/MicrosoftDocs/globalization/blob/fd6bc191ae4483fb0654e4624190a01ac5cbbbd1/globalization%2Ffonts-layout%2Fpagination.md) | 77 | 100 | 83 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96527267-ee01-4eec-8261-91bc71df2f48) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/ruby.md](https://github.com/MicrosoftDocs/globalization/blob/fd6bc191ae4483fb0654e4624190a01ac5cbbbd1/globalization%2Ffonts-layout%2Fruby.md) | 93 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80b9c96a-a50b-48c7-aa6c-0d4e4501289b) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-boundaries.md](https://github.com/MicrosoftDocs/globalization/blob/fd6bc191ae4483fb0654e4624190a01ac5cbbbd1/globalization%2Ffonts-layout%2Ftext-boundaries.md) | 89 | 100 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e683613-92a2-4450-a086-9e5dd2ba1e23) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-directionality.md](https://github.com/MicrosoftDocs/globalization/blob/fd6bc191ae4483fb0654e4624190a01ac5cbbbd1/globalization%2Ffonts-layout%2Ftext-directionality.md) | 81 | 100 | 61 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8325afd7-a810-4242-b61d-ca8a1e923e63) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-justification.md](https://github.com/MicrosoftDocs/globalization/blob/fd6bc191ae4483fb0654e4624190a01ac5cbbbd1/globalization%2Ffonts-layout%2Ftext-justification.md) | 97 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1facb77-212d-4048-8d63-26f80762e4f6) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-layout.md](https://github.com/MicrosoftDocs/globalization/blob/fd6bc191ae4483fb0654e4624190a01ac5cbbbd1/globalization%2Ffonts-layout%2Ftext-layout.md) | 84 | 100 | 70 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e0f03d9-2af9-4b26-b70a-198febe00467) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/writing-systems.md](https://github.com/MicrosoftDocs/globalization/blob/fd6bc191ae4483fb0654e4624190a01ac5cbbbd1/globalization%2Ffonts-layout%2Fwriting-systems.md) | 85 | 100 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42964eee-538d-451c-b9d1-10012a4b0ed3) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/opentype.md](https://github.com/MicrosoftDocs/globalization/blob/fd6bc191ae4483fb0654e4624190a01ac5cbbbd1/globalization%2Freference%2Fopentype.md) | 89 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b854d50-929c-4cb9-a0b7-055726818c38) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/universal-shaping-engine.md](https://github.com/MicrosoftDocs/globalization/blob/fd6bc191ae4483fb0654e4624190a01ac5cbbbd1/globalization%2Freference%2Funiversal-shaping-engine.md) | 89 | 100 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72024577-38b3-413c-810c-34cf66e23409) | [:white_check_mark:](# "Successfully processed") |
| [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/fd6bc191ae4483fb0654e4624190a01ac5cbbbd1/globalization%2Ftoc.yml) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1ddbc78-3194-4cc3-bd6d-03a66e325bfc) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2023-11-10 21:30 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/fonts-layout/displaying-text.md](https://github.com/MicrosoftDocs/globalization/blob/4315b0d5e93d547fbba7a7d4a826e38920525884/globalization%2Ffonts-layout%2Fdisplaying-text.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61a566df-7d63-4ccb-9354-97e8953e5769) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/emoji.md](https://github.com/MicrosoftDocs/globalization/blob/4315b0d5e93d547fbba7a7d4a826e38920525884/globalization%2Ffonts-layout%2Femoji.md) | 86 | 100 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7859fd6f-d21b-42e1-9159-ac7921d7b107) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/font-support.md](https://github.com/MicrosoftDocs/globalization/blob/4315b0d5e93d547fbba7a7d4a826e38920525884/globalization%2Ffonts-layout%2Ffont-support.md) | 79 | 100 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d75af90-3e86-4df1-94bf-d319448295f0) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/fonts.md](https://github.com/MicrosoftDocs/globalization/blob/4315b0d5e93d547fbba7a7d4a826e38920525884/globalization%2Ffonts-layout%2Ffonts.md) | 88 | 100 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e33f7473-8e27-41d1-9ecd-542759f64748) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/line-and-word-breaking.md](https://github.com/MicrosoftDocs/globalization/blob/4315b0d5e93d547fbba7a7d4a826e38920525884/globalization%2Ffonts-layout%2Fline-and-word-breaking.md) | 93 | 100 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20b0dcee-143e-4f18-b466-aa580d933ed6) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/multi-script-fonts.md](https://github.com/MicrosoftDocs/globalization/blob/4315b0d5e93d547fbba7a7d4a826e38920525884/globalization%2Ffonts-layout%2Fmulti-script-fonts.md) | 95 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9f7eeb2-82f7-4e83-b120-00f500b4c08d) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/pagination.md](https://github.com/MicrosoftDocs/globalization/blob/4315b0d5e93d547fbba7a7d4a826e38920525884/globalization%2Ffonts-layout%2Fpagination.md) | 77 | 100 | 83 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54d6934d-4479-41d7-a9a7-dc15123944ef) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/ruby.md](https://github.com/MicrosoftDocs/globalization/blob/4315b0d5e93d547fbba7a7d4a826e38920525884/globalization%2Ffonts-layout%2Fruby.md) | 93 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26e39a9d-8d38-4445-98be-ed8e3e3ee658) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-boundaries.md](https://github.com/MicrosoftDocs/globalization/blob/4315b0d5e93d547fbba7a7d4a826e38920525884/globalization%2Ffonts-layout%2Ftext-boundaries.md) | 89 | 100 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c58ade95-4d77-411c-9fac-5af8a511eb6c) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-directionality.md](https://github.com/MicrosoftDocs/globalization/blob/4315b0d5e93d547fbba7a7d4a826e38920525884/globalization%2Ffonts-layout%2Ftext-directionality.md) | 82 | 100 | 61 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61a6ad01-e2f2-44d2-b4f9-2f82fbca92e4) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-justification.md](https://github.com/MicrosoftDocs/globalization/blob/4315b0d5e93d547fbba7a7d4a826e38920525884/globalization%2Ffonts-layout%2Ftext-justification.md) | 97 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26ae2b42-fb3f-49aa-a92b-d11428726cab) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-layout.md](https://github.com/MicrosoftDocs/globalization/blob/4315b0d5e93d547fbba7a7d4a826e38920525884/globalization%2Ffonts-layout%2Ftext-layout.md) | 84 | 100 | 70 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bb1f8a3-5dde-4a22-be47-2ff388f00125) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/writing-systems.md](https://github.com/MicrosoftDocs/globalization/blob/4315b0d5e93d547fbba7a7d4a826e38920525884/globalization%2Ffonts-layout%2Fwriting-systems.md) | 85 | 100 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a7c4840-6f51-471a-9410-606269349451) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/opentype.md](https://github.com/MicrosoftDocs/globalization/blob/4315b0d5e93d547fbba7a7d4a826e38920525884/globalization%2Freference%2Fopentype.md) | 89 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04b7cd81-c09f-409c-ad6e-6ba46bfdfc62) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/universal-shaping-engine.md](https://github.com/MicrosoftDocs/globalization/blob/4315b0d5e93d547fbba7a7d4a826e38920525884/globalization%2Freference%2Funiversal-shaping-engine.md) | 89 | 100 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e803a3f4-0d5b-44ad-830a-ef1849090abf) | [:white_check_mark:](# "Successfully processed") |
| [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/4315b0d5e93d547fbba7a7d4a826e38920525884/globalization%2Ftoc.yml) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82d3e36c-8f63-478a-be5f-a40c648dfd25) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2023-11-10 21:45 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/fonts-layout/displaying-text.md](https://github.com/MicrosoftDocs/globalization/blob/c87625e71288abb789b78dc91f88a78ba2b82b0b/globalization%2Ffonts-layout%2Fdisplaying-text.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9859e241-8581-44b0-8fe1-1b4d161a0d32) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/emoji.md](https://github.com/MicrosoftDocs/globalization/blob/c87625e71288abb789b78dc91f88a78ba2b82b0b/globalization%2Ffonts-layout%2Femoji.md) | 86 | 100 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ceed3cd1-1794-41ce-a0fa-99b7fad637d0) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/font-support.md](https://github.com/MicrosoftDocs/globalization/blob/c87625e71288abb789b78dc91f88a78ba2b82b0b/globalization%2Ffonts-layout%2Ffont-support.md) | 79 | 100 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60e2223e-2789-4a7c-82e1-57a23d80d3dc) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/fonts.md](https://github.com/MicrosoftDocs/globalization/blob/c87625e71288abb789b78dc91f88a78ba2b82b0b/globalization%2Ffonts-layout%2Ffonts.md) | 88 | 100 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c94163b0-dc19-47eb-ab1a-1561f66ec765) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/line-and-word-breaking.md](https://github.com/MicrosoftDocs/globalization/blob/c87625e71288abb789b78dc91f88a78ba2b82b0b/globalization%2Ffonts-layout%2Fline-and-word-breaking.md) | 93 | 100 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f32319db-6902-4565-9a55-fb04e6b977da) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/multi-script-fonts.md](https://github.com/MicrosoftDocs/globalization/blob/c87625e71288abb789b78dc91f88a78ba2b82b0b/globalization%2Ffonts-layout%2Fmulti-script-fonts.md) | 95 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fa96dc9-678c-41b4-a864-2082374f7d12) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/pagination.md](https://github.com/MicrosoftDocs/globalization/blob/c87625e71288abb789b78dc91f88a78ba2b82b0b/globalization%2Ffonts-layout%2Fpagination.md) | 77 | 100 | 83 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38784bfd-8cad-4f23-a3c3-53671854d9e2) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/ruby.md](https://github.com/MicrosoftDocs/globalization/blob/c87625e71288abb789b78dc91f88a78ba2b82b0b/globalization%2Ffonts-layout%2Fruby.md) | 93 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/035d4e3a-ca77-4bb1-a5f7-5f8dcc559b92) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-boundaries.md](https://github.com/MicrosoftDocs/globalization/blob/c87625e71288abb789b78dc91f88a78ba2b82b0b/globalization%2Ffonts-layout%2Ftext-boundaries.md) | 89 | 100 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5aacfce5-eafb-44f4-9786-2d76e32d58d7) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-directionality.md](https://github.com/MicrosoftDocs/globalization/blob/c87625e71288abb789b78dc91f88a78ba2b82b0b/globalization%2Ffonts-layout%2Ftext-directionality.md) | 82 | 100 | 61 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/073a37d9-c0ca-41fb-a50f-c160954e5293) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-justification.md](https://github.com/MicrosoftDocs/globalization/blob/c87625e71288abb789b78dc91f88a78ba2b82b0b/globalization%2Ffonts-layout%2Ftext-justification.md) | 97 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f94f3c6-0f07-4c88-afd1-74fc4fe1b141) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-layout.md](https://github.com/MicrosoftDocs/globalization/blob/c87625e71288abb789b78dc91f88a78ba2b82b0b/globalization%2Ffonts-layout%2Ftext-layout.md) | 84 | 100 | 70 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7d82afd-3d0c-4b23-8bde-61d451bb1560) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/writing-systems.md](https://github.com/MicrosoftDocs/globalization/blob/c87625e71288abb789b78dc91f88a78ba2b82b0b/globalization%2Ffonts-layout%2Fwriting-systems.md) | 85 | 100 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b5ce21b-c7ab-461f-b1d1-a08be9db7277) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/opentype.md](https://github.com/MicrosoftDocs/globalization/blob/c87625e71288abb789b78dc91f88a78ba2b82b0b/globalization%2Freference%2Fopentype.md) | 89 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf04b311-155c-4670-be88-1429b3e44fb7) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/universal-shaping-engine.md](https://github.com/MicrosoftDocs/globalization/blob/c87625e71288abb789b78dc91f88a78ba2b82b0b/globalization%2Freference%2Funiversal-shaping-engine.md) | 89 | 100 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ece5f89-c03b-4f80-9055-89c217cbae03) | [:white_check_mark:](# "Successfully processed") |
| [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/c87625e71288abb789b78dc91f88a78ba2b82b0b/globalization%2Ftoc.yml) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/adf2bc43-1877-4d57-87ea-7f1b268a2df5) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2023-11-14 22:10 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/fonts-layout/displaying-text.md](https://github.com/MicrosoftDocs/globalization/blob/5033ad808e0a4e738b3db4fb1b7da0e17493dc16/globalization%2Ffonts-layout%2Fdisplaying-text.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ba9eab1-2b21-4979-bf66-6a213048df30) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/emoji.md](https://github.com/MicrosoftDocs/globalization/blob/5033ad808e0a4e738b3db4fb1b7da0e17493dc16/globalization%2Ffonts-layout%2Femoji.md) | 86 | 100 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5665b504-8552-4bd2-9771-2e0280f60999) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/font-support.md](https://github.com/MicrosoftDocs/globalization/blob/5033ad808e0a4e738b3db4fb1b7da0e17493dc16/globalization%2Ffonts-layout%2Ffont-support.md) | 79 | 100 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5cda741-83eb-4c2f-9295-e91d12a7a06e) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/fonts.md](https://github.com/MicrosoftDocs/globalization/blob/5033ad808e0a4e738b3db4fb1b7da0e17493dc16/globalization%2Ffonts-layout%2Ffonts.md) | 88 | 100 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6fa17042-cf1e-43ca-8460-63eb8d149fd8) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/line-and-word-breaking.md](https://github.com/MicrosoftDocs/globalization/blob/5033ad808e0a4e738b3db4fb1b7da0e17493dc16/globalization%2Ffonts-layout%2Fline-and-word-breaking.md) | 93 | 100 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a008cd13-e1c7-43e7-a915-ea1905f84832) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/multi-script-fonts.md](https://github.com/MicrosoftDocs/globalization/blob/5033ad808e0a4e738b3db4fb1b7da0e17493dc16/globalization%2Ffonts-layout%2Fmulti-script-fonts.md) | 95 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a92a4dc9-ce19-4dab-bc32-db623c5b1e15) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/pagination.md](https://github.com/MicrosoftDocs/globalization/blob/5033ad808e0a4e738b3db4fb1b7da0e17493dc16/globalization%2Ffonts-layout%2Fpagination.md) | 77 | 100 | 83 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/590fd462-2960-4450-9854-e23796e7049d) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/ruby.md](https://github.com/MicrosoftDocs/globalization/blob/5033ad808e0a4e738b3db4fb1b7da0e17493dc16/globalization%2Ffonts-layout%2Fruby.md) | 93 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff724eb3-5e46-4fa8-a6d8-6029c286c79c) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-boundaries.md](https://github.com/MicrosoftDocs/globalization/blob/5033ad808e0a4e738b3db4fb1b7da0e17493dc16/globalization%2Ffonts-layout%2Ftext-boundaries.md) | 89 | 100 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/661a3213-abe7-4fd8-9091-be82ae87f60f) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-directionality.md](https://github.com/MicrosoftDocs/globalization/blob/5033ad808e0a4e738b3db4fb1b7da0e17493dc16/globalization%2Ffonts-layout%2Ftext-directionality.md) | 82 | 100 | 61 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6dd122a3-ad6b-49bd-bda8-9eb40ef4c370) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-justification.md](https://github.com/MicrosoftDocs/globalization/blob/5033ad808e0a4e738b3db4fb1b7da0e17493dc16/globalization%2Ffonts-layout%2Ftext-justification.md) | 97 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b9acb48-97df-4d39-aee7-4d22996f92e6) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/text-layout.md](https://github.com/MicrosoftDocs/globalization/blob/5033ad808e0a4e738b3db4fb1b7da0e17493dc16/globalization%2Ffonts-layout%2Ftext-layout.md) | 84 | 100 | 70 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd0e36f1-d675-45ec-aee1-31db9c7ac3f0) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/writing-systems.md](https://github.com/MicrosoftDocs/globalization/blob/5033ad808e0a4e738b3db4fb1b7da0e17493dc16/globalization%2Ffonts-layout%2Fwriting-systems.md) | 85 | 100 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a64c5c54-c428-41ea-aacc-d42a7a920732) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/opentype.md](https://github.com/MicrosoftDocs/globalization/blob/5033ad808e0a4e738b3db4fb1b7da0e17493dc16/globalization%2Freference%2Fopentype.md) | 89 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/063f4643-358a-423f-9a33-142912344155) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/universal-shaping-engine.md](https://github.com/MicrosoftDocs/globalization/blob/5033ad808e0a4e738b3db4fb1b7da0e17493dc16/globalization%2Freference%2Funiversal-shaping-engine.md) | 89 | 100 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe4d9ac2-4a40-481b-a3b4-7a5ffc054166) | [:white_check_mark:](# "Successfully processed") |
| [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/5033ad808e0a4e738b3db4fb1b7da0e17493dc16/globalization%2Ftoc.yml) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4e590fd-ec4b-4b86-bf27-5076b6b5ce79) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2023-11-20 18:21 UTC, merged