56107 text support
MicrosoftDocs/globalization pull request #287
Opened 2024-01-24 23:13 UTC by jowilco

2024-01-24 23:14 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/encoding/code-pages.md](https://github.com/MicrosoftDocs/globalization/blob/7e9984b6a7eb7eb97fa939336e5c59ae6240e14f/globalization%2Fencoding%2Fcode-pages.md) | 94 | 100 | 85 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04d23e23-858c-44c6-8fb7-f2cc1c2bb84a) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/encoding-overview.md](https://github.com/MicrosoftDocs/globalization/blob/7e9984b6a7eb7eb97fa939336e5c59ae6240e14f/globalization%2Fencoding%2Fencoding-overview.md) | 89 | 100 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f55faf7-7bf2-4b31-b007-8fdea6c434e8) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/pua.md](https://github.com/MicrosoftDocs/globalization/blob/7e9984b6a7eb7eb97fa939336e5c59ae6240e14f/globalization%2Fencoding%2Fpua.md) | 82 | 100 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a713a939-b0f2-48c9-85e4-244894ab3597) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/unicode-standard.md](https://github.com/MicrosoftDocs/globalization/blob/7e9984b6a7eb7eb97fa939336e5c59ae6240e14f/globalization%2Fencoding%2Funicode-standard.md) | 79 | 58 | 81 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59e1adee-241a-48e6-93c0-661e789309fe) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/emoji.md](https://github.com/MicrosoftDocs/globalization/blob/7e9984b6a7eb7eb97fa939336e5c59ae6240e14f/globalization%2Ffonts-layout%2Femoji.md) | 92 | 100 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d3df5bf-2322-404b-acb0-716148c5940b) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/eai.md](https://github.com/MicrosoftDocs/globalization/blob/7e9984b6a7eb7eb97fa939336e5c59ae6240e14f/globalization%2Freference%2Feai.md) | 92 | 100 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b770c56-7e56-4f01-ac68-cc9dc8f0a3bc) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/idn.md](https://github.com/MicrosoftDocs/globalization/blob/7e9984b6a7eb7eb97fa939336e5c59ae6240e14f/globalization%2Freference%2Fidn.md) | 93 | 100 | 83 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d16f9ff-2bb2-44c3-8b4f-6dacc274a3f8) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/case-mapping.md](https://github.com/MicrosoftDocs/globalization/blob/7e9984b6a7eb7eb97fa939336e5c59ae6240e14f/globalization%2Ftext%2Fcase-mapping.md) | 90 | 100 | 90 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/525d155f-9c59-494f-bea5-f19a41e7e7c5) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/encoding_text_conversion.md](https://github.com/MicrosoftDocs/globalization/blob/7e9984b6a7eb7eb97fa939336e5c59ae6240e14f/globalization%2Ftext%2Fencoding_text_conversion.md) | 91 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/761f4760-ff38-4619-9542-2327e3de1121) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/parsing-input.md](https://github.com/MicrosoftDocs/globalization/blob/7e9984b6a7eb7eb97fa939336e5c59ae6240e14f/globalization%2Ftext%2Fparsing-input.md) | 92 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ac2b901-d429-4c07-a47a-bf791de72549) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/text-normalization.md](https://github.com/MicrosoftDocs/globalization/blob/7e9984b6a7eb7eb97fa939336e5c59ae6240e14f/globalization%2Ftext%2Ftext-normalization.md) | 86 | 100 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07667c4c-f7b0-4bcc-a844-d461d50f51c0) | [:white_check_mark:](# "Successfully processed") |
| [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/7e9984b6a7eb7eb97fa939336e5c59ae6240e14f/globalization%2Ftoc.yml) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/177ff848-28f7-4880-ab3b-5f48098877da) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-01-24 23:19 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/encoding/code-pages.md](https://github.com/MicrosoftDocs/globalization/blob/979a661b753227cf69faac56ff1018b5cc233df4/globalization%2Fencoding%2Fcode-pages.md) | 94 | 100 | 85 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15a58f54-4d74-4fbb-bbc1-2fa70a3af949) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/encoding-overview.md](https://github.com/MicrosoftDocs/globalization/blob/979a661b753227cf69faac56ff1018b5cc233df4/globalization%2Fencoding%2Fencoding-overview.md) | 89 | 100 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a23a59c-61c2-4762-af45-382c1ec840ac) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/pua.md](https://github.com/MicrosoftDocs/globalization/blob/979a661b753227cf69faac56ff1018b5cc233df4/globalization%2Fencoding%2Fpua.md) | 82 | 100 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31668061-e038-4579-84b0-2593175b9424) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/unicode-standard.md](https://github.com/MicrosoftDocs/globalization/blob/979a661b753227cf69faac56ff1018b5cc233df4/globalization%2Fencoding%2Funicode-standard.md) | 79 | 58 | 81 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/405c5741-65c2-4ab8-a6c4-0e85b341f15d) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/emoji.md](https://github.com/MicrosoftDocs/globalization/blob/979a661b753227cf69faac56ff1018b5cc233df4/globalization%2Ffonts-layout%2Femoji.md) | 92 | 100 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64cb5125-56a1-4ae0-be9b-272b9ba2e927) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/font-support.md](https://github.com/MicrosoftDocs/globalization/blob/979a661b753227cf69faac56ff1018b5cc233df4/globalization%2Ffonts-layout%2Ffont-support.md) | 79 | 100 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/546bf30e-08be-4112-8c71-53498c41823c) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/eai.md](https://github.com/MicrosoftDocs/globalization/blob/979a661b753227cf69faac56ff1018b5cc233df4/globalization%2Freference%2Feai.md) | 92 | 100 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/407ffd43-b9ec-4274-829e-04e2f8325cbc) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/idn.md](https://github.com/MicrosoftDocs/globalization/blob/979a661b753227cf69faac56ff1018b5cc233df4/globalization%2Freference%2Fidn.md) | 93 | 100 | 83 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5163a4e0-3eff-4204-b73a-69969eae4202) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/case-mapping.md](https://github.com/MicrosoftDocs/globalization/blob/979a661b753227cf69faac56ff1018b5cc233df4/globalization%2Ftext%2Fcase-mapping.md) | 90 | 100 | 90 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7018f4d-f34c-449e-882d-113a94012c03) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/encoding_text_conversion.md](https://github.com/MicrosoftDocs/globalization/blob/979a661b753227cf69faac56ff1018b5cc233df4/globalization%2Ftext%2Fencoding_text_conversion.md) | 91 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48144bf5-45b3-45a3-8955-07a80d936017) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/parsing-input.md](https://github.com/MicrosoftDocs/globalization/blob/979a661b753227cf69faac56ff1018b5cc233df4/globalization%2Ftext%2Fparsing-input.md) | 92 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ed00792-51e1-4ec9-9ece-fc683762e932) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/text-normalization.md](https://github.com/MicrosoftDocs/globalization/blob/979a661b753227cf69faac56ff1018b5cc233df4/globalization%2Ftext%2Ftext-normalization.md) | 86 | 100 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e43bff2d-fad6-417a-8111-9c64f3ca6853) | [:white_check_mark:](# "Successfully processed") |
| [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/979a661b753227cf69faac56ff1018b5cc233df4/globalization%2Ftoc.yml) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/085b4f92-5950-4e28-8b8a-11da75c2fa74) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-01-26 01:57 UTC, brunolewin-msft reviewed
Hi John, my first installment for "globalization/encoding". Good read, nothing blocking, just some suggestions to make easier to read.

2024-01-26 01:57 UTC, brunolewin-msft commented on globalization/encoding/unicode-standard.md
> +Both UTF-16 and UTF-32 can use little-endian (least-significant byte at the smallest memory address) or big-endian (most-significant byte at the smallest memory address) byte orders. The byte orders
Consider switching the last two sentences around to make more understandable?
"_Both UTF-16 and UTF-32 can use little-endian (least-significant byte at the smallest memory address) or big-endian (most-significant byte at the smallest memory address) byte orders s**o require a byte order mark (BOM, U+FEFF) at the beginning of the stream or file to indicate the byte order**. The byte orders for UTF-16LE, UTF-16BE, UTF-32LE, and UTF-32BE are unambiguous._"

2024-01-26 01:57 UTC, brunolewin-msft commented on globalization/encoding/unicode-standard.md
> +
Maybe add example to explain? (possibly point to https://en.wikipedia.org/wiki/UTF-16#Code_points_from_U+010000_to_U+10FFFF or similar)

2024-01-26 01:57 UTC, brunolewin-msft commented on globalization/encoding/unicode-standard.md
> +The code-point positions of Unicode elements don't imply a [sort order](../locale/sorting-and-string-comparison.md) and the organization is often unrelated to language usage. To implement sorting, th
"the organization is often unrelated to language usage" is hard to understand

2024-01-26 17:36 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/encoding/code-pages.md](https://github.com/MicrosoftDocs/globalization/blob/692522ee0c48f237c3e0c8f7088e40e95e949f22/globalization%2Fencoding%2Fcode-pages.md) | 94 | 100 | 85 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/489e1515-e2f8-49c7-bc1b-10bc8c03abde) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/encoding-overview.md](https://github.com/MicrosoftDocs/globalization/blob/692522ee0c48f237c3e0c8f7088e40e95e949f22/globalization%2Fencoding%2Fencoding-overview.md) | 91 | 100 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43ec80fb-1c30-498f-9fc6-439a7ed24931) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/pua.md](https://github.com/MicrosoftDocs/globalization/blob/692522ee0c48f237c3e0c8f7088e40e95e949f22/globalization%2Fencoding%2Fpua.md) | 82 | 100 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed83a07c-8e9f-4607-bee6-b93f212aa96f) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/unicode-standard.md](https://github.com/MicrosoftDocs/globalization/blob/692522ee0c48f237c3e0c8f7088e40e95e949f22/globalization%2Fencoding%2Funicode-standard.md) | 79 | 59 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36c0acd7-28dc-4e85-9ef7-2b3a06ac1460) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/emoji.md](https://github.com/MicrosoftDocs/globalization/blob/692522ee0c48f237c3e0c8f7088e40e95e949f22/globalization%2Ffonts-layout%2Femoji.md) | 92 | 100 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54184299-603f-44d9-8a40-98d9181cbbb0) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/font-support.md](https://github.com/MicrosoftDocs/globalization/blob/692522ee0c48f237c3e0c8f7088e40e95e949f22/globalization%2Ffonts-layout%2Ffont-support.md) | 79 | 100 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/538a5b8a-678f-416f-9d3f-df30118d2cd2) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/eai.md](https://github.com/MicrosoftDocs/globalization/blob/692522ee0c48f237c3e0c8f7088e40e95e949f22/globalization%2Freference%2Feai.md) | 92 | 100 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9d9950f-c6f2-4bd3-8c14-bf634109d928) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/idn.md](https://github.com/MicrosoftDocs/globalization/blob/692522ee0c48f237c3e0c8f7088e40e95e949f22/globalization%2Freference%2Fidn.md) | 93 | 100 | 83 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c216f0c2-aabe-4e55-a6f5-957186b28761) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/case-mapping.md](https://github.com/MicrosoftDocs/globalization/blob/692522ee0c48f237c3e0c8f7088e40e95e949f22/globalization%2Ftext%2Fcase-mapping.md) | 90 | 100 | 90 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/063e3249-65bc-4af1-86d4-383f119823f0) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/encoding_text_conversion.md](https://github.com/MicrosoftDocs/globalization/blob/692522ee0c48f237c3e0c8f7088e40e95e949f22/globalization%2Ftext%2Fencoding_text_conversion.md) | 91 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ef0998e-d690-45b3-9a70-e41f88dcfdee) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/parsing-input.md](https://github.com/MicrosoftDocs/globalization/blob/692522ee0c48f237c3e0c8f7088e40e95e949f22/globalization%2Ftext%2Fparsing-input.md) | 92 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f20f0199-b304-40a6-af4a-334b09f35fe0) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/text-normalization.md](https://github.com/MicrosoftDocs/globalization/blob/692522ee0c48f237c3e0c8f7088e40e95e949f22/globalization%2Ftext%2Ftext-normalization.md) | 86 | 100 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22ba10fd-4d9c-4e4e-a826-5e15239a5ac7) | [:white_check_mark:](# "Successfully processed") |
| [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/692522ee0c48f237c3e0c8f7088e40e95e949f22/globalization%2Ftoc.yml) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1b1ea27-a9e6-48b9-acc6-dfb0ba8e386e) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-01-26 17:55 UTC, jowilco commented on globalization/encoding/code-pages.md
> +
I had really wanted to find the Microsoft information and duplicate that, but it doesn't seem to exist. I don't want to copy someone else's graphic or data. I could generate my own table from code, but these are easy enough to look up elsewhere.

2024-01-26 17:56 UTC, jowilco commented on globalization/encoding/code-pages.md
> +
Done

2024-01-26 18:08 UTC, agustd requested changes
Great articles. Brilliant to see Ghostwriter in action for our documents.

2024-01-26 18:22 UTC, jowilco commented on globalization/encoding/encoding-overview.md
> +Most modern computers work with and store binary numbers in groups of 8 bits. These computers have no intrinsic knowledge of characters used in [writing systems](../fonts-layout/writing-systems.md).
Reordered, but kept. I want to keep the comparison because of 7-bit ANSI.

2024-01-26 18:23 UTC, jowilco commented on globalization/encoding/encoding-overview.md
> +
Added a sample line rather than a full table.

2024-01-26 18:23 UTC, jowilco commented on globalization/encoding/encoding-overview.md
> +To allow for the storage of characters that support different writing systems in the same data stream, [Unicode](unicode-standard.md) was created. Unicode can represent over 64,000 characters, and wi
Changed.

2024-01-26 18:23 UTC, jowilco commented on globalization/encoding/encoding-overview.md
> +
Added.

2024-01-26 18:25 UTC, jowilco commented on globalization/encoding/code-pages.md
> +Most applications written today handle character data primarily as [Unicode](unicode-standard.md), using one of several encodings such as UTF-8 or UTF-16LE. Windows supports several of these encoding
Removed, and added a short intro for Unicode.

2024-01-26 18:27 UTC, jowilco commented on globalization/encoding/unicode-standard.md
> +Both UTF-16 and UTF-32 can use little-endian (least-significant byte at the smallest memory address) or big-endian (most-significant byte at the smallest memory address) byte orders. The byte orders
Switched order and tweaked the styling to try to differentiate where we are talking about UTF-16 as a 16-bit encoding and UTF-16 as the actual name of the encoding scheme.

2024-01-26 18:28 UTC, jowilco commented on globalization/encoding/unicode-standard.md
> +
Added an example

2024-01-26 22:22 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/encoding/code-pages.md](https://github.com/MicrosoftDocs/globalization/blob/755da90c945d368c65f699ce748469be497dad1c/globalization%2Fencoding%2Fcode-pages.md) | 94 | 100 | 85 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a54717e-e05c-4ec8-81c5-770006b00adc) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/encoding-overview.md](https://github.com/MicrosoftDocs/globalization/blob/755da90c945d368c65f699ce748469be497dad1c/globalization%2Fencoding%2Fencoding-overview.md) | 91 | 100 | 90 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f518d22-7202-43cc-81c3-93ade6bb9893) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/pua.md](https://github.com/MicrosoftDocs/globalization/blob/755da90c945d368c65f699ce748469be497dad1c/globalization%2Fencoding%2Fpua.md) | 82 | 100 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84d26191-6243-49bc-8f94-63140d6a2589) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/unicode-standard.md](https://github.com/MicrosoftDocs/globalization/blob/755da90c945d368c65f699ce748469be497dad1c/globalization%2Fencoding%2Funicode-standard.md) | 79 | 59 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36323920-5a3c-443a-973a-a9bac9aaae60) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/emoji.md](https://github.com/MicrosoftDocs/globalization/blob/755da90c945d368c65f699ce748469be497dad1c/globalization%2Ffonts-layout%2Femoji.md) | 92 | 100 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da5f43e1-21c0-42a1-9382-141806db9511) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/font-support.md](https://github.com/MicrosoftDocs/globalization/blob/755da90c945d368c65f699ce748469be497dad1c/globalization%2Ffonts-layout%2Ffont-support.md) | 79 | 100 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f95ecd82-067d-48e1-8a6c-705ef74021e0) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/eai.md](https://github.com/MicrosoftDocs/globalization/blob/755da90c945d368c65f699ce748469be497dad1c/globalization%2Freference%2Feai.md) | 92 | 100 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d600984a-8016-4ff4-acb2-261938b9a88e) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/idn.md](https://github.com/MicrosoftDocs/globalization/blob/755da90c945d368c65f699ce748469be497dad1c/globalization%2Freference%2Fidn.md) | 93 | 100 | 83 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a521d18-940b-434f-9804-38fd83df2920) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/case-mapping.md](https://github.com/MicrosoftDocs/globalization/blob/755da90c945d368c65f699ce748469be497dad1c/globalization%2Ftext%2Fcase-mapping.md) | 90 | 100 | 90 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3971e4b6-d636-4edc-a435-281412a0199c) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/encoding_text_conversion.md](https://github.com/MicrosoftDocs/globalization/blob/755da90c945d368c65f699ce748469be497dad1c/globalization%2Ftext%2Fencoding_text_conversion.md) | 91 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20b06646-31a7-420d-b772-00468b45f39b) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/parsing-input.md](https://github.com/MicrosoftDocs/globalization/blob/755da90c945d368c65f699ce748469be497dad1c/globalization%2Ftext%2Fparsing-input.md) | 92 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38e0b23a-c5c0-4a39-8792-dc4d453ebb9b) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/text-normalization.md](https://github.com/MicrosoftDocs/globalization/blob/755da90c945d368c65f699ce748469be497dad1c/globalization%2Ftext%2Ftext-normalization.md) | 86 | 100 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6a28216-92eb-4a9e-8d86-a9f2dbdbfe06) | [:white_check_mark:](# "Successfully processed") |
| [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/755da90c945d368c65f699ce748469be497dad1c/globalization%2Ftoc.yml) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b375aacb-096e-498a-8835-b27f7c7997de) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-01-26 22:23 UTC, jowilco commented on globalization/text/parsing-input.md
> +There are extra concerns when parsing and storing dates and times. For example, a scheduling application might allow users in different countries or regions to schedule meetings together. It's best p
Good catch! I had a link in the Word document, but didn't migrate the link when I migrated the text to Markdown.
Fixed.

2024-01-29 18:20 UTC, jowilco commented on globalization/reference/eai.md
> +When using EAI, the local-part of the email address is still limited in the use of whether specific characters can appear outside of quotation marks as defined in RFC 5322. For example, an email addr
On hold, per discussion with @agustd.
Any (valid) example that we pick *could* be used by someone.

2024-01-29 18:20 UTC, jowilco commented on globalization/reference/eai.md
> +Support of EAI is largely dependent on the email server. For example, an email server might support sending emails to an address using EAI; however, the same email server doesn't have to support host
On hold, per discussion with @agustd.
Any (valid) example that we pick *could* be used by someone.

2024-01-29 18:24 UTC, jowilco commented on globalization/reference/idn.md
> +While IDN enables the support of domain names using scripts other than Latin, these domain names are stored in DNS as ASCII strings using [Punycode](https://www.rfc-editor.org/rfc/rfc3492.txt) transc
On hold, per discussion with @agustd.
Any (valid) example that we pick *could* be used by someone.
In theory, we could use a domain like micrŏsoft.com as an example, and show the equivalent Punycode, BUT that would implicitly be a spoofing attack.

2024-01-29 22:41 UTC, brunolewin-msft reviewed
I'm done with the review. Excellent. I mostly put optional suggestions for clarity, except for parsing-input where I suggested some changes to the structure (feel free to ping me if easier than read through that longish comment)

2024-01-29 22:41 UTC, brunolewin-msft commented on globalization/text/parsing-input.md
> +Locales specify the decimal and grouping separator used to format numbers. Windows allows users to select the list separator, which can also be used as the default delimiter for applications to suppo
This felt confusing, esp. given that by default, for en-US, Excel uses comma as separator, which is also the US grouping separator.  Consider being more direct and call out that there are 3 distinct challenges when parsing data from a file:
- figure out the encoding (your other topic)
- figure out the separator (which may vary depending on locale or user's choice)
- interpret the individual element  (parsing numbers, times, dates)

2024-01-29 22:41 UTC, brunolewin-msft commented on globalization/text/parsing-input.md
> +There are extra concerns when parsing and storing dates and times. For example, a scheduling application might allow users in different countries or regions to schedule meetings together. It's best p
True, but feels a bit off topic in the context of "Parsing Input". Maybe present the challenge more explicitly, calling out that in the case of date/time, in addition to the initial **parsing** challenge when reading text that represents time/date, there is also a consideration of user intent - e.g. need to figure when a time is meant as local time irrespective of DST (e.g. set alarm for 6am) v/s absolute time (data logging) that may determine how to **store**.

2024-01-29 22:41 UTC, brunolewin-msft commented on globalization/text/encoding_text_conversion.md
> +---
This complements the articles in globalization/encoding very nicely. Should this be rolled into that section or at least get some links?

2024-01-30 00:29 UTC, jowilco commented on globalization/text/parsing-input.md
> +In general, it's best practice to assume that numbers, dates, and times are entered in a format that corresponds to a format supported by the current application locale. There are occasions where you
Note that "local" application would not be correct, but I have changed this to "For both desktop and web applications".

2024-01-30 00:36 UTC, jowilco commented on globalization/text/encoding_text_conversion.md
> +---
Added links

2024-01-30 00:42 UTC, jowilco commented on globalization/text/parsing-input.md
> +There are extra concerns when parsing and storing dates and times. For example, a scheduling application might allow users in different countries or regions to schedule meetings together. It's best p
I'm not sure that user intent does matter in your alarm example; when a user asks for an alarm to be set at 6am for the next day, and the next day has the DST shift applied, the user should still be woken up at 6 am (now obviously this is a different issue if they want to be woken up at 2 am (which 2 am?)).

2024-01-30 00:48 UTC, jowilco commented on globalization/text/parsing-input.md
> +Locales specify the decimal and grouping separator used to format numbers. Windows allows users to select the list separator, which can also be used as the default delimiter for applications to suppo
My goal here was to identify that in addition to decimal and grouping separators, Windows provides a list separator, which is not (say) part of ICU.
The problem in your example above is that both of these are valid for French:
|-- | --|
|CSV saved with Windows set to English (United States) locale: | 1.2,3.4,"1,000,000.01"|
|CSV saved with Windows set to French (France) locale: | 1,2;3,4;1 000 000,01|
|CSV saved with Windows set to French (France) locale: | "1,2","3,4","1 000 000,01"|

I'm not saying that I'd recommend the second one, but it is valid CSV.

But I do get your point - when parsing CSV consider separation before worrying about elements.

2024-01-30 01:18 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/encoding/code-pages.md](https://github.com/MicrosoftDocs/globalization/blob/a75031f34b730ed5cd36778dfaabe8f96d6a09ac/globalization%2Fencoding%2Fcode-pages.md) | 94 | 100 | 85 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6e56f67-6a75-415a-a341-4704140a413c) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/encoding-overview.md](https://github.com/MicrosoftDocs/globalization/blob/a75031f34b730ed5cd36778dfaabe8f96d6a09ac/globalization%2Fencoding%2Fencoding-overview.md) | 91 | 100 | 90 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9006958d-74b1-4df5-be11-8ba0f987b8ed) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/pua.md](https://github.com/MicrosoftDocs/globalization/blob/a75031f34b730ed5cd36778dfaabe8f96d6a09ac/globalization%2Fencoding%2Fpua.md) | 82 | 100 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba3ee5f9-4f0d-4c23-8d51-51cb4a7018fd) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/unicode-standard.md](https://github.com/MicrosoftDocs/globalization/blob/a75031f34b730ed5cd36778dfaabe8f96d6a09ac/globalization%2Fencoding%2Funicode-standard.md) | 79 | 59 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/793a8c3e-77d9-4696-bf9b-def8b25a877e) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/emoji.md](https://github.com/MicrosoftDocs/globalization/blob/a75031f34b730ed5cd36778dfaabe8f96d6a09ac/globalization%2Ffonts-layout%2Femoji.md) | 92 | 100 | 63 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae8306bf-b204-4f4e-9042-04d19f9d831a) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/font-support.md](https://github.com/MicrosoftDocs/globalization/blob/a75031f34b730ed5cd36778dfaabe8f96d6a09ac/globalization%2Ffonts-layout%2Ffont-support.md) | 79 | 100 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3cb134c-f7c5-494d-ad9f-818604c8e3e3) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/eai.md](https://github.com/MicrosoftDocs/globalization/blob/a75031f34b730ed5cd36778dfaabe8f96d6a09ac/globalization%2Freference%2Feai.md) | 92 | 100 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/109dc264-948c-4887-8f7f-7ecf8040314e) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/idn.md](https://github.com/MicrosoftDocs/globalization/blob/a75031f34b730ed5cd36778dfaabe8f96d6a09ac/globalization%2Freference%2Fidn.md) | 93 | 100 | 83 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a833835-d8c5-48c9-9e80-972d5853bdd1) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/case-mapping.md](https://github.com/MicrosoftDocs/globalization/blob/a75031f34b730ed5cd36778dfaabe8f96d6a09ac/globalization%2Ftext%2Fcase-mapping.md) | 90 | 100 | 90 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4955f8da-4575-42dc-8a01-ca2f2f2b7e12) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/encoding_text_conversion.md](https://github.com/MicrosoftDocs/globalization/blob/a75031f34b730ed5cd36778dfaabe8f96d6a09ac/globalization%2Ftext%2Fencoding_text_conversion.md) | 91 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c28d2341-fdc0-42fd-a97d-cb95f0d7bb18) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/parsing-input.md](https://github.com/MicrosoftDocs/globalization/blob/a75031f34b730ed5cd36778dfaabe8f96d6a09ac/globalization%2Ftext%2Fparsing-input.md) | 87 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4fc9fc3c-3bef-41de-b56b-5b71d9c0846c) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/text-normalization.md](https://github.com/MicrosoftDocs/globalization/blob/a75031f34b730ed5cd36778dfaabe8f96d6a09ac/globalization%2Ftext%2Ftext-normalization.md) | 86 | 100 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c09af66f-9fea-4d47-9031-901365a8fe92) | [:white_check_mark:](# "Successfully processed") |
| [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/a75031f34b730ed5cd36778dfaabe8f96d6a09ac/globalization%2Ftoc.yml) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2592221-0191-480c-b663-5b64d4a08bc5) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-01-30 16:34 UTC, brunolewin-msft commented on globalization/text/parsing-input.md
> +In general, it's best practice to assume that numbers, dates, and times are entered in a format that corresponds to a format supported by the current application locale. There are occasions where you
"local" might not be best wording, but it was meant to specifically distinguish apps running on the user's device (desktop, tablet, phone, etc - cases where "current application locale" is nearly always tied to the user's locale) from server apps or services where the application locale is often not the same as the locale of the user and some other mechanism is needed to handle the user's formatting preference.

2024-01-30 22:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/encoding/code-pages.md](https://github.com/MicrosoftDocs/globalization/blob/37e47aa5c53327da2a5e8f9633a5191007dd6fe0/globalization%2Fencoding%2Fcode-pages.md) | 94 | 100 | 85 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb66acf6-0297-4bdc-bd97-912be89fb413) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/encoding-overview.md](https://github.com/MicrosoftDocs/globalization/blob/37e47aa5c53327da2a5e8f9633a5191007dd6fe0/globalization%2Fencoding%2Fencoding-overview.md) | 91 | 100 | 90 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ffe65352-86f6-4cb9-a4e9-8c8c3eb0d6be) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/pua.md](https://github.com/MicrosoftDocs/globalization/blob/37e47aa5c53327da2a5e8f9633a5191007dd6fe0/globalization%2Fencoding%2Fpua.md) | 82 | 100 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8319e63c-dab8-46e8-a6a4-5550bb0acdd5) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/unicode-standard.md](https://github.com/MicrosoftDocs/globalization/blob/37e47aa5c53327da2a5e8f9633a5191007dd6fe0/globalization%2Fencoding%2Funicode-standard.md) | 79 | 59 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/371dfdf8-0c75-4503-a7e6-7473d86f636e) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/emoji.md](https://github.com/MicrosoftDocs/globalization/blob/37e47aa5c53327da2a5e8f9633a5191007dd6fe0/globalization%2Ffonts-layout%2Femoji.md) | 92 | 100 | 63 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97c88735-0c6e-4590-a2a5-0fcc68341c34) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/font-support.md](https://github.com/MicrosoftDocs/globalization/blob/37e47aa5c53327da2a5e8f9633a5191007dd6fe0/globalization%2Ffonts-layout%2Ffont-support.md) | 79 | 100 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/414e170f-6fc2-4e72-9763-3b08c7023df0) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/eai.md](https://github.com/MicrosoftDocs/globalization/blob/37e47aa5c53327da2a5e8f9633a5191007dd6fe0/globalization%2Freference%2Feai.md) | 92 | 100 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/045db4fb-59b2-4b38-9e21-a9c4f7c0c94c) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/idn.md](https://github.com/MicrosoftDocs/globalization/blob/37e47aa5c53327da2a5e8f9633a5191007dd6fe0/globalization%2Freference%2Fidn.md) | 93 | 100 | 83 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e0a956e-fb5f-43c7-8cbe-fe0f1a365943) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/case-mapping.md](https://github.com/MicrosoftDocs/globalization/blob/37e47aa5c53327da2a5e8f9633a5191007dd6fe0/globalization%2Ftext%2Fcase-mapping.md) | 90 | 100 | 90 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/132fad70-acf4-4574-b967-6ef257ddd7bc) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/encoding_text_conversion.md](https://github.com/MicrosoftDocs/globalization/blob/37e47aa5c53327da2a5e8f9633a5191007dd6fe0/globalization%2Ftext%2Fencoding_text_conversion.md) | 91 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8dc4b95f-eac3-485c-84f6-84047e402f05) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/parsing-input.md](https://github.com/MicrosoftDocs/globalization/blob/37e47aa5c53327da2a5e8f9633a5191007dd6fe0/globalization%2Ftext%2Fparsing-input.md) | 95 | 100 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bdfc1696-3c27-48e8-af91-1fb27e1f976e) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/text-normalization.md](https://github.com/MicrosoftDocs/globalization/blob/37e47aa5c53327da2a5e8f9633a5191007dd6fe0/globalization%2Ftext%2Ftext-normalization.md) | 86 | 100 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7cf83138-eaea-4820-8815-aa9b14d625fd) | [:white_check_mark:](# "Successfully processed") |
| [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/37e47aa5c53327da2a5e8f9633a5191007dd6fe0/globalization%2Ftoc.yml) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/796946c8-ac51-40c1-a690-2af84e8a0442) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-01-30 22:58 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/encoding/code-pages.md](https://github.com/MicrosoftDocs/globalization/blob/9936e287ac41b92d635822555946e782f0ceaa11/globalization%2Fencoding%2Fcode-pages.md) | 94 | 100 | 85 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c5e6f3b-b8ce-4fd4-8927-c9539e9f0b0f) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/encoding-overview.md](https://github.com/MicrosoftDocs/globalization/blob/9936e287ac41b92d635822555946e782f0ceaa11/globalization%2Fencoding%2Fencoding-overview.md) | 91 | 100 | 90 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e45ab773-5e9c-42ba-9d69-881c9f650803) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/pua.md](https://github.com/MicrosoftDocs/globalization/blob/9936e287ac41b92d635822555946e782f0ceaa11/globalization%2Fencoding%2Fpua.md) | 82 | 100 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99b17945-763b-4205-9654-1816007c4cdf) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/unicode-standard.md](https://github.com/MicrosoftDocs/globalization/blob/9936e287ac41b92d635822555946e782f0ceaa11/globalization%2Fencoding%2Funicode-standard.md) | 79 | 59 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/852ecc54-1871-4116-bddc-ac8169d6fdb1) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/emoji.md](https://github.com/MicrosoftDocs/globalization/blob/9936e287ac41b92d635822555946e782f0ceaa11/globalization%2Ffonts-layout%2Femoji.md) | 92 | 100 | 63 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f62ebec5-3b6e-47a9-a313-8d8cc4b0ce76) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/font-support.md](https://github.com/MicrosoftDocs/globalization/blob/9936e287ac41b92d635822555946e782f0ceaa11/globalization%2Ffonts-layout%2Ffont-support.md) | 79 | 100 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e23c85f6-6265-49ad-ad78-1eedb797ec85) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/eai.md](https://github.com/MicrosoftDocs/globalization/blob/9936e287ac41b92d635822555946e782f0ceaa11/globalization%2Freference%2Feai.md) | 92 | 100 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82ea52e5-e6a7-41f2-bb9b-7b48ede91746) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/idn.md](https://github.com/MicrosoftDocs/globalization/blob/9936e287ac41b92d635822555946e782f0ceaa11/globalization%2Freference%2Fidn.md) | 93 | 100 | 83 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/569846cc-604f-4aaa-a220-dcd0973cdd7f) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/case-mapping.md](https://github.com/MicrosoftDocs/globalization/blob/9936e287ac41b92d635822555946e782f0ceaa11/globalization%2Ftext%2Fcase-mapping.md) | 90 | 100 | 90 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1671e460-9476-48dd-a401-a022a35eb8eb) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/encoding_text_conversion.md](https://github.com/MicrosoftDocs/globalization/blob/9936e287ac41b92d635822555946e782f0ceaa11/globalization%2Ftext%2Fencoding_text_conversion.md) | 91 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6953dfb-4f60-4d84-9078-55370e3e07b3) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/parsing-input.md](https://github.com/MicrosoftDocs/globalization/blob/9936e287ac41b92d635822555946e782f0ceaa11/globalization%2Ftext%2Fparsing-input.md) | 95 | 100 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a56020c-b1cc-4a15-a21f-a8c4dcdda459) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/text-normalization.md](https://github.com/MicrosoftDocs/globalization/blob/9936e287ac41b92d635822555946e782f0ceaa11/globalization%2Ftext%2Ftext-normalization.md) | 86 | 100 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50d11f5c-d320-4690-84f0-c68463f2f384) | [:white_check_mark:](# "Successfully processed") |
| [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/9936e287ac41b92d635822555946e782f0ceaa11/globalization%2Ftoc.yml) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5df87af6-4aae-4ee9-9469-1a3f045e69cf) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-01-30 23:17 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/encoding/code-pages.md](https://github.com/MicrosoftDocs/globalization/blob/f058316b463d1d2aef4636d3923c6239a654d71d/globalization%2Fencoding%2Fcode-pages.md) | 94 | 100 | 85 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2551550e-d491-4c7b-9e43-9793442ac4cc) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/encoding-overview.md](https://github.com/MicrosoftDocs/globalization/blob/f058316b463d1d2aef4636d3923c6239a654d71d/globalization%2Fencoding%2Fencoding-overview.md) | 91 | 100 | 90 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46f56836-ab9b-4ae4-9054-9633e15c39ec) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/pua.md](https://github.com/MicrosoftDocs/globalization/blob/f058316b463d1d2aef4636d3923c6239a654d71d/globalization%2Fencoding%2Fpua.md) | 82 | 100 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b53f5b68-784e-455b-bd09-90bc93f9acd4) | [:white_check_mark:](# "Successfully processed") |
| [globalization/encoding/unicode-standard.md](https://github.com/MicrosoftDocs/globalization/blob/f058316b463d1d2aef4636d3923c6239a654d71d/globalization%2Fencoding%2Funicode-standard.md) | 79 | 59 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82de9575-125a-4a02-ae12-eaf919e47869) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/emoji.md](https://github.com/MicrosoftDocs/globalization/blob/f058316b463d1d2aef4636d3923c6239a654d71d/globalization%2Ffonts-layout%2Femoji.md) | 92 | 100 | 63 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4017a247-364a-4021-adf6-29b44d4521e8) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/font-support.md](https://github.com/MicrosoftDocs/globalization/blob/f058316b463d1d2aef4636d3923c6239a654d71d/globalization%2Ffonts-layout%2Ffont-support.md) | 79 | 100 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87b66635-3486-4f54-9a29-eb06fd8685ae) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/eai.md](https://github.com/MicrosoftDocs/globalization/blob/f058316b463d1d2aef4636d3923c6239a654d71d/globalization%2Freference%2Feai.md) | 92 | 100 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f63b1cf1-0464-44dc-89f8-0edd7e599488) | [:white_check_mark:](# "Successfully processed") |
| [globalization/reference/idn.md](https://github.com/MicrosoftDocs/globalization/blob/f058316b463d1d2aef4636d3923c6239a654d71d/globalization%2Freference%2Fidn.md) | 93 | 100 | 83 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25ebaacf-d5a2-4ae8-b986-876f48cfe581) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/case-mapping.md](https://github.com/MicrosoftDocs/globalization/blob/f058316b463d1d2aef4636d3923c6239a654d71d/globalization%2Ftext%2Fcase-mapping.md) | 90 | 100 | 90 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fdcb5939-2a1e-47c1-9e40-4d9f84e3174c) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/encoding_text_conversion.md](https://github.com/MicrosoftDocs/globalization/blob/f058316b463d1d2aef4636d3923c6239a654d71d/globalization%2Ftext%2Fencoding_text_conversion.md) | 91 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd69fd0d-c58e-4bd9-a4eb-01da33798c6b) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/parsing-input.md](https://github.com/MicrosoftDocs/globalization/blob/f058316b463d1d2aef4636d3923c6239a654d71d/globalization%2Ftext%2Fparsing-input.md) | 95 | 100 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9d7b93a-a279-4dc1-9689-84e44529fdc7) | [:white_check_mark:](# "Successfully processed") |
| [globalization/text/text-normalization.md](https://github.com/MicrosoftDocs/globalization/blob/f058316b463d1d2aef4636d3923c6239a654d71d/globalization%2Ftext%2Ftext-normalization.md) | 86 | 100 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c168ed2-3202-4c07-b175-b742798f2926) | [:white_check_mark:](# "Successfully processed") |
| [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/f058316b463d1d2aef4636d3923c6239a654d71d/globalization%2Ftoc.yml) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e29b54c-dab5-4dc3-9773-d8ff4031dabe) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-02-02 18:39 UTC, agustd approved these changes

2024-02-02 18:40 UTC, merged

2024-02-02 20:08 UTC, brunolewin-msft commented
[celebrate]     Bruno Lewin (Centific Technolo... reacted to your message:
________________________________
From: John Wilcock ***@***.***>
Sent: Friday, February 2, 2024 6:40:44 PM
To: MicrosoftDocs/globalization ***@***.***>
Cc: Bruno Lewin (Centific Technologies Inc) ***@***.***>; Review requested ***@***.***>
Subject: Re: [MicrosoftDocs/globalization] 56107 text support (PR #287)


Merged #287<https://github.com/MicrosoftDocs/globalization/pull/287> into startup-staging.

—
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/globalization/pull/287#event-11687825907>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AEKVIQC33EWBV46USSE7YHLYRUXKZAVCNFSM6AAAAABCJSFVTOVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJRGY4DOOBSGU4TANY>.
You are receiving this because your review was requested.Message ID: ***@***.***>