56133 56196 resources and UI
MicrosoftDocs/globalization pull request #297
Opened 2024-03-27 16:05 UTC by jowilco

2024-03-27 16:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/fonts-layout/adaptive-ui.md](https://github.com/MicrosoftDocs/globalization/blob/1e4e0edf7bff9c0fbcb0623c97ab2038190ee12d/globalization%2Ffonts-layout%2Fadaptive-ui.md) | 95 | 100 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b62b475e-4e88-416a-9727-ab4972159307) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/images-icons-colors.md](https://github.com/MicrosoftDocs/globalization/blob/1e4e0edf7bff9c0fbcb0623c97ab2038190ee12d/globalization%2Ffonts-layout%2Fimages-icons-colors.md) | 93 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba80ef34-62d6-4e9b-abc4-ac75c196f8bc) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/interface-layout.md](https://github.com/MicrosoftDocs/globalization/blob/1e4e0edf7bff9c0fbcb0623c97ab2038190ee12d/globalization%2Ffonts-layout%2Finterface-layout.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4728de4f-e2c1-4435-bc4e-0c996f3c9e6e) | [:white_check_mark:](# "Successfully processed") |
| [globalization/fonts-layout/mirroring.md](https://github.com/MicrosoftDocs/globalization/blob/1e4e0edf7bff9c0fbcb0623c97ab2038190ee12d/globalization%2Ffonts-layout%2Fmirroring.md) | 94 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d532ef27-9c37-48c5-ba50-f1a69e454360) | [:white_check_mark:](# "Successfully processed") |
| [globalization/internationalization/concatenation.md](https://github.com/MicrosoftDocs/globalization/blob/1e4e0edf7bff9c0fbcb0623c97ab2038190ee12d/globalization%2Finternationalization%2Fconcatenation.md) | 74 | 100 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/838d909d-0340-4de7-8a3f-4da3d3221b82) | [:white_check_mark:](# "Successfully processed") |
| [globalization/internationalization/contextual-metadata.md](https://github.com/MicrosoftDocs/globalization/blob/1e4e0edf7bff9c0fbcb0623c97ab2038190ee12d/globalization%2Finternationalization%2Fcontextual-metadata.md) | 82 | 100 | 89 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa7baa09-8d68-4ccf-bdd0-a1024ef3ff75) | [:white_check_mark:](# "Successfully processed") |
| [globalization/internationalization/externalize-resources.md](https://github.com/MicrosoftDocs/globalization/blob/1e4e0edf7bff9c0fbcb0623c97ab2038190ee12d/globalization%2Finternationalization%2Fexternalize-resources.md) | 96 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36cc5c2c-7834-44fd-a6ac-e18e56102538) | [:white_check_mark:](# "Successfully processed") |
| [globalization/internationalization/message-formatting.md](https://github.com/MicrosoftDocs/globalization/blob/1e4e0edf7bff9c0fbcb0623c97ab2038190ee12d/globalization%2Finternationalization%2Fmessage-formatting.md) | 88 | 100 | 85 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94ca6dcb-85b5-4c09-b8d5-29c185a3d1ed) | [:white_check_mark:](# "Successfully processed") |
| [globalization/internationalization/pluralization.md](https://github.com/MicrosoftDocs/globalization/blob/1e4e0edf7bff9c0fbcb0623c97ab2038190ee12d/globalization%2Finternationalization%2Fpluralization.md) | 75 | 100 | 73 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7522e00-ec02-45cb-9e7c-f9760e2b54ec) | [:white_check_mark:](# "Successfully processed") |
| [globalization/methodology/software-internationalization.md](https://github.com/MicrosoftDocs/globalization/blob/1e4e0edf7bff9c0fbcb0623c97ab2038190ee12d/globalization%2Fmethodology%2Fsoftware-internationalization.md) | 94 | 100 | 93 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8dd9207-184f-438e-9cbf-3110450ff5cd) | [:white_check_mark:](# "Successfully processed") |
| [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/1e4e0edf7bff9c0fbcb0623c97ab2038190ee12d/globalization%2Ftoc.yml) | 99 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82f30cb0-c04e-446a-b8dd-6fd48bab69c1) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-03-27 16:19 UTC, brunolewin-msft commented
I like the GW changes in 7fb8860713d45e5e456ded55acf1fe41a6b00e82 :)

2024-03-27 16:23 UTC, agustd commented on globalization/fonts-layout/images-icons-colors.md
>  # Images, icons, and colors
Not sure if for this iteration or future ones but, would you think that there will be specific i18n advantages in using vector images as opposed to raster ones, or even character-based icons as opposed to image-based ones?

2024-03-27 16:27 UTC, jowilco commented on globalization/fonts-layout/images-icons-colors.md
>  # Images, icons, and colors
I think that this really depends on the context. At a previous company, we had automation that would generate multiple thousands of (raster) screenshots in all target languages; however, we also had a small amount of vector art (think flowcharts or illustrative images) that we translated as SVG.
I'm not sure that vector is "better" than raster. It really depends on the use case.

2024-03-27 16:34 UTC, brunolewin-msft commented on globalization/fonts-layout/interface-layout.md
> +For languages such as Arabic and Hebrew that use right-to-left scripts, UI layouts implemented for these languages must also support the natural [right-to left directionality](text-directionality.md)
_Consider shortening:_
For languages such as Arabic and Hebrew that use right-to-left scripts, the UI layout should follow the natural [right-to left directionality](text-directionality.md).

2024-03-27 16:43 UTC, brunolewin-msft commented on globalization/fonts-layout/interface-layout.md
> +UI design involves using [icons, images, and colors](images-icons-colors.md)  to convey the brand experience and to guide the user through your application. When you're creating icons and images, the
_Minor - consider shortening:_
UI design involves using [icons, images, and colors](images-icons-colors.md) to convey the brand experience and to guide the user through your application. In addition to standard design language considerations such as meaning, sizing, alignment, and consistency, consider potential cultural issues in target markets worldwide.

2024-03-27 16:44 UTC, agustd requested changes
Only added a potential addition to image mirroring. Great documents.

2024-03-27 16:44 UTC, agustd commented on globalization/fonts-layout/mirroring.md
> +For RTL languages, user interface elements should also follow the natural direction of right to left. By default, edit controls in a right-to-left document should inherit right-to-left behavior. For
It might be worth calling out that not all images/icons need to be mirrored. There are a few exceptions, like the play button for media.

2024-03-27 16:48 UTC, brunolewin-msft commented on globalization/fonts-layout/adaptive-ui.md
> +User interfaces for Win32 applications are implemented via the Microsoft Windows [Resource Compiler](/windows/win32/menurc/resource-compiler) and its associated [resource files](/windows/win32/menurc
Starting with Win32 might make this feel a bit dated. Consider starting with something like "Historically..." to also strengthen the contrast with the next paragraph that cover current best practices.

2024-03-27 17:04 UTC, brunolewin-msft commented on globalization/fonts-layout/adaptive-ui.md
> +One of the advantages of these responsive design techniques for localization is that controls like [Label](/dotnet/api/microsoft.maui.controls.label) and [Button](/dotnet/api/microsoft.maui.controls.
_Consider making it more explicit that responsive UI can make each language look good w/o need for specific resizing **IF** you follow best practices - e.g.:_  
One of the advantages of these responsive design techniques for localization is that controls like [Label](/dotnet/api/microsoft.maui.controls.label) and [Button](/dotnet/api/microsoft.maui.controls.button) can resize,  wrap, or move depending on the length of the text, without need to manually adapt positions and dimensions for each language. To achieve this, a best practice is to test for text expansion using techniques like [pseudolocalization](../methodology/pseudolocalization.md). For more information about text for UI controls, see [Message formatting](../internationalization/message-formatting.md).

2024-03-27 18:58 UTC, brunolewin-msft commented on globalization/fonts-layout/mirroring.md
> +- Touch optimization. Like touch UI in nonmirrored UI, elements are easy to reach, and they natural to touch interaction.
Not sure if I understand what **Touch optimization** involves for bidi specifically from this. Suggest to either remove or clarify with an example.

2024-03-27 19:02 UTC, brunolewin-msft commented on globalization/fonts-layout/mirroring.md
> +When ensuring support for bidirectional text in applications, you should validate:
_That sentence sounds like it could apply to support for bidi text in an application that is not localized into a bidi language. If that was the intent, it should not be under a "mirroring" heading. Otherwise, suggest:_
To support UI in bidirectional languages, you should validate:

2024-03-27 20:42 UTC, brunolewin-msft commented on globalization/fonts-layout/mirroring.md
> +For more information about designing applications to support bidirectional text and mirroring, see [Design your app for bidirectional text](/windows/apps/design/globalizing/design-for-bidi-text) and
The second link ([Adjust layout and fonts, and support RTL](/windows/apps/design/globalizing/adjust-layout-and-fonts--and-support-rtl)) seems very tech-specific so might work better in the next section.

2024-03-27 20:52 UTC, brunolewin-msft commented on globalization/fonts-layout/mirroring.md
> +For RTL languages, user interface elements should also follow the natural direction of right to left. By default, edit controls in a right-to-left document should inherit right-to-left behavior. For
Agree with above. More generally, I'm not finding any great info about what to do with **graphics** so spelling out the guiding principle of which graphics should be same as in LTR version, which should be mirrored and which need re-design would be valuable.  To Agustin's point, the specific **play button** case is nicely discussed in the link provided further down ( [Design your app for bidirectional text](/windows/apps/design/globalizing/design-for-bidi-text) ) but that article does not cover really cover the general principle, and some of the examples (e.g. the growth chart graphic not bring mirrored) are questionable.

2024-03-27 21:25 UTC, brunolewin-msft commented on globalization/internationalization/concatenation.md
> +
I really like this article. We could even add declensions for good measure 😊

### Declensions

In English, nouns generally don’t change as context changes. For example, "I see **a car**", "I use **a car**". In Polish, the noun may change depending on other elements of the sentence. For example, "Widzę **samochód**", "Używam **samochodu**".

Again, while it might be tempting to use variables to generate strings, declensions are another aspect that can make this very challenging to implement correctly in other languages.

2024-03-27 21:30 UTC, brunolewin-msft commented on globalization/internationalization/pluralization.md
> +
Suggest adding a note along the lines of "Make sure to coordinate with your localization team when planning your implementation" as some loc tools/workflow may struggle to handle some implementations of pluralization.

2024-03-27 21:31 UTC, brunolewin-msft commented on globalization/internationalization/message-formatting.md
> +With a few exceptions, memory isn't the primary consideration when authoring resources. Best practice is to **never** concatenating strings. Even when there are many cases, write out each sentence co
"concatenating" -->"concatenate"

2024-03-27 21:37 UTC, brunolewin-msft commented on globalization/internationalization/message-formatting.md
> +Instead, you should use a separate string for every instance.
_maybe add:_
Ensure you have a mechanism in place to provide translators with context so they can translate each instance correctly. See [Contextual metadata](contextual-metadata.md).

2024-03-27 21:42 UTC, brunolewin-msft commented on globalization/internationalization/externalize-resources.md
> +Nonlocalizable text is common in extensible applications. Identifiers such as class names, keywords, functions, and database table names fall into this category. If such a string is localized, then s
_Consider clarifying:_
"If such a string is localized, then scripts and extensions become incompatible between locales." --> "If such a string is localized, then scripts and extensions become incompatible between different language versions of the application."

2024-03-27 21:50 UTC, brunolewin-msft commented on globalization/internationalization/contextual-metadata.md
> +  <value>{0} is required.</value>
This example is using the type of concatenation we say should be avoided elsewhere and the comment is not very understandable. Maybe consider using the example of the two instances of "bookmark"  (noun and verb) mentioned earlier instead for this RESX sample?

2024-03-27 21:57 UTC, brunolewin-msft commented on globalization/internationalization/contextual-metadata.md
> +
_Consider adding something along the lines of:_
Ensure that the strings that will fill a placeholder also have a comment that indicates where they will be used.

2024-03-27 21:58 UTC, brunolewin-msft commented on globalization/internationalization/contextual-metadata.md
> +In partnership with your localization vendor and the computer-aided translation or translation management system, you might be able to use contextual metadata to specify behavior for how strings are
Consider clarifying this as we're saying elsewhere to not include such strings in resources. 😊

2024-03-27 22:03 UTC, brunolewin-msft commented on globalization/internationalization/contextual-metadata.md
> +While it's often best practice to add contextual metadata to most strings, you should focus on adding contextual metadata where it adds value. Your goal should be to provide translators enough inform
_Consider rephrasing_ 
"While it's often best practice to add contextual metadata to most strings, you should focus on adding contextual metadata where it adds value." --> "Do not add contextual metadata to every string as that could be counterproductive. Instead, you should focus on adding contextual metadata where it adds value."

2024-03-28 17:17 UTC, brunolewin-msft commented on globalization/methodology/software-internationalization.md
>  ---
@jowilco - about **methodology/software-internationalization.md** as a whole. The new content feels extremely similar to [methodology/international-design](https://review.learn.microsoft.com/en-us/globalization/methodology/international-design) and the latter feels easier to read, so wonder if it would be best to just remove **methodology/software-internationalization.md** and possibly tweak **methodology/international-design** a bit

2024-04-05 20:56 UTC, jowilco commented on globalization/fonts-layout/interface-layout.md
> +For languages such as Arabic and Hebrew that use right-to-left scripts, UI layouts implemented for these languages must also support the natural [right-to left directionality](text-directionality.md)
Implemented.

2024-04-05 20:57 UTC, jowilco commented on globalization/fonts-layout/interface-layout.md
> +UI design involves using [icons, images, and colors](images-icons-colors.md)  to convey the brand experience and to guide the user through your application. When you're creating icons and images, the
Implemented

2024-04-05 21:05 UTC, jowilco commented on globalization/fonts-layout/mirroring.md
> +For RTL languages, user interface elements should also follow the natural direction of right to left. By default, edit controls in a right-to-left document should inherit right-to-left behavior. For
I added the following: Note that not all images and icons should be mirrored. For example, common icons such as the fast-forward and rewind icons in media players, use the same orientation in both LTR and RTL layouts.

2024-04-05 21:07 UTC, jowilco commented on globalization/fonts-layout/adaptive-ui.md
> +User interfaces for Win32 applications are implemented via the Microsoft Windows [Resource Compiler](/windows/win32/menurc/resource-compiler) and its associated [resource files](/windows/win32/menurc
Reused the second sentence, and moved it before the first sentence as so: Historically, user interfaces were specified using a coordinate system with a specified position, height, and width for each control.

2024-04-05 21:09 UTC, jowilco commented on globalization/fonts-layout/adaptive-ui.md
> +One of the advantages of these responsive design techniques for localization is that controls like [Label](/dotnet/api/microsoft.maui.controls.label) and [Button](/dotnet/api/microsoft.maui.controls.
Implemented

2024-04-05 21:10 UTC, jowilco commented on globalization/fonts-layout/mirroring.md
> +- Touch optimization. Like touch UI in nonmirrored UI, elements are easy to reach, and they natural to touch interaction.
Added "like on-screen keyboards"

2024-04-05 21:12 UTC, jowilco commented on globalization/fonts-layout/mirroring.md
> +When ensuring support for bidirectional text in applications, you should validate:
Implemented.

2024-04-05 21:16 UTC, jowilco commented on globalization/internationalization/concatenation.md
> +
Added! And gave you credit as an author.

2024-04-05 21:22 UTC, jowilco commented on globalization/internationalization/pluralization.md
> +
Done. And gave you credit again, which I should have done for the Przeczytałeś {formattedCount} artykułu. example.

2024-04-05 21:22 UTC, jowilco commented on globalization/internationalization/message-formatting.md
> +With a few exceptions, memory isn't the primary consideration when authoring resources. Best practice is to **never** concatenating strings. Even when there are many cases, write out each sentence co
Done

2024-04-05 21:23 UTC, brunolewin-msft commented on globalization/fonts-layout/mirroring.md
> +- Touch optimization. Like touch UI in nonmirrored UI, elements are easy to reach, and they natural to touch interaction.
@jowilco - I meant that it’s not obvious **what needs to be taken into consideration** for a touch UI (not what a touch UI is)

2024-04-05 21:23 UTC, jowilco commented on globalization/internationalization/message-formatting.md
> +Instead, you should use a separate string for every instance.
Done.

2024-04-05 21:25 UTC, jowilco commented on globalization/internationalization/externalize-resources.md
> +Nonlocalizable text is common in extensible applications. Identifiers such as class names, keywords, functions, and database table names fall into this category. If such a string is localized, then s
Done.

2024-04-05 21:28 UTC, jowilco commented on globalization/internationalization/contextual-metadata.md
> +  <value>{0} is required.</value>
Done

2024-04-05 21:30 UTC, jowilco commented on globalization/internationalization/contextual-metadata.md
> +
Done

2024-04-05 21:31 UTC, jowilco commented on globalization/internationalization/contextual-metadata.md
> +In partnership with your localization vendor and the computer-aided translation or translation management system, you might be able to use contextual metadata to specify behavior for how strings are
I don't think that we say that. I think that we recommend keeping non-translatable strings separate from translatable strings. However, I rephrased to "strings or portions of a string..."

2024-04-05 21:33 UTC, jowilco commented on globalization/internationalization/contextual-metadata.md
> +While it's often best practice to add contextual metadata to most strings, you should focus on adding contextual metadata where it adds value. Your goal should be to provide translators enough inform
I'm leery of using something as absolute as "Do not add.... to every string..." It's up to them if they want to add metadata for every string. But it will be a waste of time for many strings.

2024-04-05 21:35 UTC, jowilco commented on globalization/methodology/software-internationalization.md
>  ---
I felt that the current file (methodology/international-design) is WAY too long for an introductory topic, and is a mix of concepts and details.
My goal of software-internationalization.md was to give a quick overview with links to the real content.

2024-04-05 21:39 UTC, jowilco commented on globalization/fonts-layout/mirroring.md
> +- Touch optimization. Like touch UI in nonmirrored UI, elements are easy to reach, and they natural to touch interaction.
Agreed. The context is that touch UI controls, such as OSK, shouldn't overlap elements of your UI in RTL if they don't overlap in LTR.

2024-04-05 21:40 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum total score of 80 is required.**
 
Select the total score link to review all feedback on clarity, consistency, tone, brand, terms, spelling, grammar, readability, and inclusive language. _You should fix all spelling errors regardless of your total score_. Fixing spelling errors helps maintain customer trust in overall content quality.

| Article | Total score<br>(Required: 80) | Words + phrases<br>(Brand, terms) | Correctness<br>(Spelling, grammar) | Clarity<br>(Readability) |
|---------|:--------------:|:--------------------:|:------:|:---------:|
| [:white_check_mark:](# "Successfully processed") [globalization/fonts-layout/adaptive-ui.md](https://github.com/MicrosoftDocs/globalization/blob/bfb6a367f88259146babeae220e9950b71646c99/globalization%2Ffonts-layout%2Fadaptive-ui.md) | [89](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c62055ab-9d62-4dad-8152-8255de7d5024) | 100 | 78 | 67 |
| [:white_check_mark:](# "Successfully processed") [globalization/fonts-layout/images-icons-colors.md](https://github.com/MicrosoftDocs/globalization/blob/bfb6a367f88259146babeae220e9950b71646c99/globalization%2Ffonts-layout%2Fimages-icons-colors.md) | [93](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ba59e2b-a497-4803-9f2b-3ad5c822f7fb) | 100 | 100 | 75 |
| [:white_check_mark:](# "Successfully processed") [globalization/fonts-layout/interface-layout.md](https://github.com/MicrosoftDocs/globalization/blob/bfb6a367f88259146babeae220e9950b71646c99/globalization%2Ffonts-layout%2Finterface-layout.md) | [100](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14a16cb8-4540-4be5-b07d-f235e7b995a6) | 100 | 100 | 100 |
| [:white_check_mark:](# "Successfully processed") [globalization/fonts-layout/mirroring.md](https://github.com/MicrosoftDocs/globalization/blob/bfb6a367f88259146babeae220e9950b71646c99/globalization%2Ffonts-layout%2Fmirroring.md) | [93](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70e6606b-f198-4fed-9481-15e144c534cd) | 100 | 100 | 66 |
| [:white_check_mark:](# "Successfully processed") [globalization/internationalization/concatenation.md](https://github.com/MicrosoftDocs/globalization/blob/bfb6a367f88259146babeae220e9950b71646c99/globalization%2Finternationalization%2Fconcatenation.md) | [75](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2f2c277-4945-4e0a-96e6-00147ac11153) | 100 | 55 | 71 |
| [:white_check_mark:](# "Successfully processed") [globalization/internationalization/contextual-metadata.md](https://github.com/MicrosoftDocs/globalization/blob/bfb6a367f88259146babeae220e9950b71646c99/globalization%2Finternationalization%2Fcontextual-metadata.md) | [81](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3fadbb3-de9e-4d99-88f2-90f9e6b3ddc0) | 100 | 90 | 52 |
| [:white_check_mark:](# "Successfully processed") [globalization/internationalization/externalize-resources.md](https://github.com/MicrosoftDocs/globalization/blob/bfb6a367f88259146babeae220e9950b71646c99/globalization%2Finternationalization%2Fexternalize-resources.md) | [96](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d1406a5-256f-4a0d-bd02-f33f0de7e5f4) | 100 | 100 | 83 |
| [:white_check_mark:](# "Successfully processed") [globalization/internationalization/message-formatting.md](https://github.com/MicrosoftDocs/globalization/blob/bfb6a367f88259146babeae220e9950b71646c99/globalization%2Finternationalization%2Fmessage-formatting.md) | [88](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/badd97eb-9699-482f-ac94-c107a3cbfe8f) | 100 | 85 | 58 |
| [:white_check_mark:](# "Successfully processed") [globalization/internationalization/pluralization.md](https://github.com/MicrosoftDocs/globalization/blob/bfb6a367f88259146babeae220e9950b71646c99/globalization%2Finternationalization%2Fpluralization.md) | [76](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd8d3d91-1ede-40a6-9864-82ab537aaec5) | 100 | 77 | 65 |
| [:white_check_mark:](# "Successfully processed") [globalization/methodology/software-internationalization.md](https://github.com/MicrosoftDocs/globalization/blob/bfb6a367f88259146babeae220e9950b71646c99/globalization%2Fmethodology%2Fsoftware-internationalization.md) | [94](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f2a8ea1-22c7-45d6-9304-42d0fc24a7ff) | 100 | 93 | 78 |
| [:white_check_mark:](# "Successfully processed") [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/bfb6a367f88259146babeae220e9950b71646c99/globalization%2Ftoc.yml) | [99](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6617d33-2808-46d1-92a5-786de2d70769) | 100 | 100 | 95 |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-04-05 21:52 UTC, brunolewin-msft commented on globalization/internationalization/contextual-metadata.md
> +While it's often best practice to add contextual metadata to most strings, you should focus on adding contextual metadata where it adds value. Your goal should be to provide translators enough inform
Fair. Maybe "There may be no need to add contextual metadata to every string.  you should focus on adding contextual metadata where it adds value." to be more nuanced and drive the point?

2024-04-05 22:05 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum total score of 80 is required.**
 
Select the total score link to review all feedback on clarity, consistency, tone, brand, terms, spelling, grammar, readability, and inclusive language. _You should fix all spelling errors regardless of your total score_. Fixing spelling errors helps maintain customer trust in overall content quality.

| Article | Total score<br>(Required: 80) | Words + phrases<br>(Brand, terms) | Correctness<br>(Spelling, grammar) | Clarity<br>(Readability) |
|---------|:--------------:|:--------------------:|:------:|:---------:|
| [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") [globalization/fonts-layout/adaptive-ui.md](https://github.com/MicrosoftDocs/globalization/blob/e399dcbdb709ffa81849c8da8d78cde31d5ae0ed/globalization%2Ffonts-layout%2Fadaptive-ui.md) | [ ]( ) |   |   |   |
| [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") [globalization/fonts-layout/images-icons-colors.md](https://github.com/MicrosoftDocs/globalization/blob/e399dcbdb709ffa81849c8da8d78cde31d5ae0ed/globalization%2Ffonts-layout%2Fimages-icons-colors.md) | [ ]( ) |   |   |   |
| [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") [globalization/fonts-layout/interface-layout.md](https://github.com/MicrosoftDocs/globalization/blob/e399dcbdb709ffa81849c8da8d78cde31d5ae0ed/globalization%2Ffonts-layout%2Finterface-layout.md) | [ ]( ) |   |   |   |
| [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") [globalization/fonts-layout/mirroring.md](https://github.com/MicrosoftDocs/globalization/blob/e399dcbdb709ffa81849c8da8d78cde31d5ae0ed/globalization%2Ffonts-layout%2Fmirroring.md) | [ ]( ) |   |   |   |
| [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") [globalization/internationalization/concatenation.md](https://github.com/MicrosoftDocs/globalization/blob/e399dcbdb709ffa81849c8da8d78cde31d5ae0ed/globalization%2Finternationalization%2Fconcatenation.md) | [ ]( ) |   |   |   |
| [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") [globalization/internationalization/contextual-metadata.md](https://github.com/MicrosoftDocs/globalization/blob/e399dcbdb709ffa81849c8da8d78cde31d5ae0ed/globalization%2Finternationalization%2Fcontextual-metadata.md) | [ ]( ) |   |   |   |
| [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") [globalization/internationalization/externalize-resources.md](https://github.com/MicrosoftDocs/globalization/blob/e399dcbdb709ffa81849c8da8d78cde31d5ae0ed/globalization%2Finternationalization%2Fexternalize-resources.md) | [ ]( ) |   |   |   |
| [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") [globalization/internationalization/message-formatting.md](https://github.com/MicrosoftDocs/globalization/blob/e399dcbdb709ffa81849c8da8d78cde31d5ae0ed/globalization%2Finternationalization%2Fmessage-formatting.md) | [ ]( ) |   |   |   |
| [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") [globalization/internationalization/pluralization.md](https://github.com/MicrosoftDocs/globalization/blob/e399dcbdb709ffa81849c8da8d78cde31d5ae0ed/globalization%2Finternationalization%2Fpluralization.md) | [ ]( ) |   |   |   |
| [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") [globalization/methodology/software-internationalization.md](https://github.com/MicrosoftDocs/globalization/blob/e399dcbdb709ffa81849c8da8d78cde31d5ae0ed/globalization%2Fmethodology%2Fsoftware-internationalization.md) | [ ]( ) |   |   |   |
| [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/e399dcbdb709ffa81849c8da8d78cde31d5ae0ed/globalization%2Ftoc.yml) | [ ]( ) |   |   |   |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-04-05 22:10 UTC, agustd approved these changes

2024-04-08 18:24 UTC, merged