Validation articles
MicrosoftDocs/globalization pull request #301
Opened 2024-04-10 13:12 UTC by m-kauppinen

Updated localizability testing and localization testing articles and TOC.

2024-04-10 13:12 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum total score of 80 is required.**
 
Select the total score link to review all feedback on clarity, consistency, tone, brand, terms, spelling, grammar, readability, and inclusive language. _You should fix all spelling errors regardless of your total score_. Fixing spelling errors helps maintain customer trust in overall content quality.

| Article | Total score<br>(Required: 80) | Words + phrases<br>(Brand, terms) | Correctness<br>(Spelling, grammar) | Clarity<br>(Readability) |
|---------|:--------------:|:--------------------:|:------:|:---------:|
| [:white_check_mark:](# "Successfully processed") [globalization/methodology/how-to-validate-internationalized-products.md](https://github.com/MicrosoftDocs/globalization/blob/13b98baaade2d5c80cc4a994ac1070b18792cab1/globalization%2Fmethodology%2Fhow-to-validate-internationalized-products.md) | [90](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e162523f-50a9-434e-96e6-ec25668168b6) | 100 | 100 | 55 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/how-to-test-internationalized-products.md](https://github.com/MicrosoftDocs/globalization/blob/13b98baaade2d5c80cc4a994ac1070b18792cab1/globalization%2Ftesting%2Fhow-to-test-internationalized-products.md) | [91](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c53cb616-cd72-42d8-9ab9-d8c8d6d43b26) | 100 | 100 | 57 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/how-to-test.md](https://github.com/MicrosoftDocs/globalization/blob/13b98baaade2d5c80cc4a994ac1070b18792cab1/globalization%2Ftesting%2Fhow-to-test.md) | [89](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be61f7fb-8806-4b80-a45b-f27928b4a924) | 100 | 96 | 78 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/what-to-look-for-when-testing.md](https://github.com/MicrosoftDocs/globalization/blob/13b98baaade2d5c80cc4a994ac1070b18792cab1/globalization%2Ftesting%2Fwhat-to-look-for-when-testing.md) | [93](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae18190e-9c79-4d8e-89c3-04f7759c830d) | 100 | 89 | 86 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/when-to-test.md](https://github.com/MicrosoftDocs/globalization/blob/13b98baaade2d5c80cc4a994ac1070b18792cab1/globalization%2Ftesting%2Fwhen-to-test.md) | [89](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be4c3ef6-09db-433b-b0f7-243cde740102) | 100 | 94 | 54 |
| [:white_check_mark:](# "Successfully processed") [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/13b98baaade2d5c80cc4a994ac1070b18792cab1/globalization%2Ftoc.yml) | [99](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2453e498-c95d-4544-8536-57826aa995f1) | 100 | 100 | 95 |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-04-11 12:18 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum total score of 80 is required.**
 
Select the total score link to review all feedback on clarity, consistency, tone, brand, terms, spelling, grammar, readability, and inclusive language. _You should fix all spelling errors regardless of your total score_. Fixing spelling errors helps maintain customer trust in overall content quality.

| Article | Total score<br>(Required: 80) | Words + phrases<br>(Brand, terms) | Correctness<br>(Spelling, grammar) | Clarity<br>(Readability) |
|---------|:--------------:|:--------------------:|:------:|:---------:|
| [:white_check_mark:](# "Successfully processed") [globalization/methodology/how-to-validate-internationalized-products.md](https://github.com/MicrosoftDocs/globalization/blob/4d535938f8b129e4e8d6d2a15e320cc8db44af21/globalization%2Fmethodology%2Fhow-to-validate-internationalized-products.md) | [90](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f81a1f32-0007-44f8-8bab-7702ad3f1ace) | 100 | 100 | 55 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/how-to-test-internationalized-products.md](https://github.com/MicrosoftDocs/globalization/blob/4d535938f8b129e4e8d6d2a15e320cc8db44af21/globalization%2Ftesting%2Fhow-to-test-internationalized-products.md) | [91](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24219c02-d1f2-480e-a3ef-14c36b5b2887) | 100 | 100 | 57 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/how-to-test.md](https://github.com/MicrosoftDocs/globalization/blob/4d535938f8b129e4e8d6d2a15e320cc8db44af21/globalization%2Ftesting%2Fhow-to-test.md) | [89](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/926063d7-0817-41bf-94da-31c865af646e) | 100 | 96 | 78 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/what-to-look-for-when-testing.md](https://github.com/MicrosoftDocs/globalization/blob/4d535938f8b129e4e8d6d2a15e320cc8db44af21/globalization%2Ftesting%2Fwhat-to-look-for-when-testing.md) | [93](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06180086-7003-4b52-af01-0dfac4f76061) | 100 | 89 | 86 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/when-to-test.md](https://github.com/MicrosoftDocs/globalization/blob/4d535938f8b129e4e8d6d2a15e320cc8db44af21/globalization%2Ftesting%2Fwhen-to-test.md) | [89](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65333a5d-56e1-441c-ac03-a3bd2f93928f) | 100 | 94 | 54 |
| [:white_check_mark:](# "Successfully processed") [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/4d535938f8b129e4e8d6d2a15e320cc8db44af21/globalization%2Ftoc.yml) | [99](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/754d55d4-1f4d-45a5-b436-7528d650e502) | 100 | 100 | 95 |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-04-11 18:07 UTC, brunolewin-msft commented
From a quick first pass: this is good content, with opportunities to make it easier on the readers by tweaking the organization.

Thinking e.g. 
- more obvious distinction between planning (=what areas need to be validated, how to distribute that work across teams/companies, etc - **this could be beefed up**) and execution considerations (tying validation activities to existing docs about int'l reqs - **this is mostly there**). 
- more obvious/consistent distinction between areas as defined in other articles - e.g. the [methodology article](https://review.learn.microsoft.com/en-us/globalization/methodology/how-to-validate-internationalized-products?branch=pr-en-us-301) does a great job re-using items covered in [Software Internationalization](https://review.learn.microsoft.com/en-us/globalization/methodology/software-internationalization?branch=pr-en-us-301) but is presenting them under "**localizability**" and paraphrasing, so it's not immediately obvious that we're covering the same thing.  
- finally, there are some great nuggets of info that could be made more discoverable (e.g. the point about **latency and local hosting** that's currently below localization testing, and probably deserves to be called out as a separate area)

Will be reading in more detail, but want to check if that sounds right, @jowilco @m-kauppinen as a lot of my detailed feedback might be in that general direction.

2024-04-16 16:43 UTC, brunolewin-msft reviewed
First batch of comments, mostly focused on:
- globalization/methodology/how-to-validate-internationalized-products.md
- globalization/testing/how-to-test-internationalized-products.md
- globalization/testing/what-to-look-for-when-testing.md

2024-04-16 18:12 UTC, brunolewin-msft commented on globalization/testing/when-to-test.md
> +title: When to test internationalized products
**General comment**: the article contains some good planning points, **a lot** of very good content about **localizability validation**, some good points about globalization. It's good content, but the article as a whole could be improved as: 
- it's not immediately clear if this is an article about planning (based on its title) or about localizability validation (based on the bulk of the content).  
- it overlaps with [What to look for when testing internationalized products](https://review.learn.microsoft.com/en-us/globalization/testing/what-to-look-for-when-testing?branch=pr-en-us-301)  
- "localizability" seems to refer to _things that should ideally happen before localization start_ - would suggest limiting to _things that enable localization_ (e.g. externalizing resources, commenting, etc are included, but things like regional format support, text handling, etc are excluded) 

My initial thought is that this would read much better if split into distinct
- When to test (this could be rolled into the more general [Validating products for international release](https://review.learn.microsoft.com/en-us/globalization/testing/how-to-test-internationalized-products?branch=pr-en-us-301) or standalone article)
-  Localizability testing (content would be the bulk of this article, with planning & globalization bits removed and with matching title)

2024-04-16 18:39 UTC, brunolewin-msft commented on globalization/testing/when-to-test.md
> +However, bugs and other issues are often more apparent after the translations have been implemented. Localization is expensive, so it’s usually done after the code is complete and stable enough. Ther
Suggest nuancing this to account for modern continuous localization practices.

"However, bugs and other issues are often more apparent after the translations have been implemented. Localization is expensive, so it’s usually done after the code is complete and stable enough. There's inevitably a gap between an app's development and its localization." -->"However, some bugs and other issues may become more apparent after translations has been completed. The goal is too minimize the number and severity of issues found after translation, to reduce late rework, but is typically not a full substitute for validating localized versions."

2024-04-16 18:50 UTC, brunolewin-msft commented on globalization/testing/when-to-test.md
> +
The following have a mix of "localizability" items (5  - which has a great reference to the actual list of things to look for, possibly 6) and ones that we did not define as localizability. If the focus of the article is on localizability, I'd suggest either removing the non-localizability items OR possibly moving them to the end of the list with a heading along the lines of "_These can be done at the same time as reviewing code for general internationalization, including..._" 

Another option could be to just take the existing [Localizability checklist](https://review.learn.microsoft.com/en-us/globalization/testing/what-to-look-for-when-testing?branch=pr-en-us-301#localizability) and explain how to apply it in the context of a code review.

2024-04-16 18:59 UTC, brunolewin-msft commented on globalization/testing/when-to-test.md
> +You should ensure the terminology used in your app’s user interface and support documentation is clear, consistent, and unambiguous. Translators find it harder to do a good job if the UI and the docu
This is a great point. **Minor:** since we've said above that this should be part of the CR (point 5, first item of the linked list - "_Text and messages are devoid of jargon, slang, and cultural references_"), it would be good to call out how this broader effort complements that work and helps ensure consistency across components of a product.

2024-04-16 19:15 UTC, brunolewin-msft commented on globalization/testing/when-to-test.md
> +This review phase becomes even more important if your localizability testing relies on pseudolocalization. It works well to find code, string handling, and layout problems in your app, but is less ef
**Minor:** possibly confusing as (i) we have not introduced pseudo localization yet and (ii) specialized tools do a pretty good job on terminology management & consistency checks. This could probably be removed and we could possibly call some of the limitations of pseudo in the next section, if that was the intent.

2024-04-16 19:33 UTC, brunolewin-msft commented on globalization/testing/when-to-test.md
> +Pseudolocalization (informally, "pseudo") can be the most effective way of finding localizability bugs that would only be detected when translating your app. Pseudolocalization gives you a "translati
Suggest calling out the other key benefits, something along the lines of:
 
"_Some localizability issues such as truncations, concatenation or strings that are not exposed to localization are easier to spot on a pseudolocalized version than on a real language. And unlike a real translated version, a pseudolocalized version is easy to use even if you don't understand other real languages._"

2024-04-16 19:38 UTC, brunolewin-msft commented on globalization/testing/when-to-test.md
> +Once you pseudolocalize your app, [test its functionality](how-to-test.md). A pseudolocalized app should function exactly like its source language version. Besides detecting localizability bugs, pseu
The linked article is not really about functional testing :)

Suggest:
"Once you have pseudolocalized your product, [test it as you would a real language](how-to-test.md), covering both functional and visual aspects, paying special attention to [localizability issues](what-to-look-for-when-testing.md#localizability)."

2024-04-16 20:10 UTC, brunolewin-msft commented on globalization/testing/when-to-test.md
> +As discussed previously, [pseudolocalization](#test-with-a-pseudolocalized-version-of-your-app) can be extremely helpful, but it can never catch all issues. If you start the actual localization with
Suggest:
"_If you start the actual localization with a small release, you'll identify more issues than with pseudolocalization alone. The most effective approach is to do both._" 
-->
"_If you complete a validation through pseudolocalization (and address issues that have been found), then start the actual localization and localization testing with a small subset of pilot languages, you may identify additional issues before they impact your broader localization efforts. These typically include issues that specifically impact the translation process, ranging from tooling to challenges with the source text._"

2024-04-16 20:27 UTC, brunolewin-msft commented on globalization/testing/when-to-test.md
> +Every language is different, and localizing just one or two can't reveal every possible issue. But combined with the above phases, it gives you a solid foundation for localizing your complete languag
per previous comment, suggest tweaking below:

"_But combined with the above phases, it gives you a solid foundation for localizing your complete language set. It needs to be weighed against your overall goal, however, which is usually shipping as many languages as possible as soon as possible._" 
--> 
"_Adding pseudolocalization and pilot localization may seem like extra steps that could slow down the pace of planned localized releases. When combined strategically, each step can significantly reduce the effort required in the next step, especially with a large number of target languages. This can not only reduce costs, it can also speed up the release of each planned language **at the right quality** by dramatically shortening its validation and bug fixing cycle._"

2024-04-16 20:38 UTC, brunolewin-msft commented on globalization/testing/how-to-test.md
> +This article discusses the methods and tools for testing your localized products. For information about localizability testing, that is, what you should validate before starting localization, see [Wh
Suggest:

"_For information about localizability testing, that is, what you should validate before starting localization, see [When to test internationalized products](when-to-test.md) and [What to look for when testing internationalized products](what-to-look-for-when-testing.md)_."
-->

"_It assumes that you have already planned for validation of other aspects of [internationalization](what-to-look-for-when-testing.md), especially [localizability validation](when-to-test.md), that are typically a prerequisite to effective localization testing._"

2024-04-16 20:42 UTC, brunolewin-msft commented on globalization/testing/how-to-test.md
> +[Pseudolocalization](../methodology/pseudolocalization.md) is a powerful tool for uncovering many issues during localizability testing. When you [test for localizability](when-to-test.md) before you
Suggest removing above paragraph as this is well covered in the localizability article.

2024-04-16 20:51 UTC, brunolewin-msft commented on globalization/testing/how-to-test.md
> +Localization testing checks how well your product is translated into a particular target language. Localization testing is an extension of [localizability testing](when-to-test.md), where the functio
I like the link with localizability. Suggest making the definition consistent with what we say elsewhere, i.e. loc testing = cosmetic, linguistic and functional aspects.

"_Localization testing checks how well your product is translated into a particular target language. Localization testing is an extension of [localizability testing](when-to-test.md), where the functional support for locales was already verified._"
-->
"_Localization testing checks how well your product is translated into a particular target language and confirms that there are no visual or functional issues. Ideally, [localizability testing](when-to-test.md) has already uncovered most visual and functional issues that could impact localized versions, and these have been addressed before localization testing._"

2024-04-16 21:50 UTC, agustd submitted a review, later dismissed
Nothing to add. Bruno's comments covered much more that I could have probably commented on.

2024-04-16 23:29 UTC, brunolewin-msft requested changes
Thanks for a great read, @m-kauppinen - I'm done with my comments. Note this was quite hard to review as the content was generally very good, but I struggled with the way things flowed within and across articles or how we ordered the different complementary validation activities - that's the bulk of comments, sorry that these are quite long. I also made some somewhat preferential tweaks based on my own preference on how to approach i18n testing. FYI @jowilco

2024-04-16 23:29 UTC, brunolewin-msft commented on globalization/testing/how-to-test.md
> +### Localization testing for UI and language
Suggest renaming to "**Visual validation**" and moving out the "linguistic accuracy" point (covered in the linguistic section)

2024-04-16 23:29 UTC, brunolewin-msft commented on globalization/testing/how-to-test.md
> +The second consists of culture-specific, language-specific, and country- or region-specific areas. Examples include configurable components such as region defaults and the default language, as well a
**Suggest moving these 3 paragraphs to a new "**Other risk areas**" section**

The second consists of culture-specific, language-specific, and country- or region-specific areas. Examples include configurable components such as region defaults and the default language, as well as language-specific and region- or market-specific functionality, for example, spelling checkers and speech engines. You should also test the availability of drivers for local hardware.

Pay specific attention to customization that couldn't be automated using the infrastructure provided by your platform or language globalization services. For example, check that the formatting of mailing addresses matches the locale conventions.



You also need to check that everything you're going to release to a new target market complies with the local laws and regulations. This includes not only the license agreement but also any user documentation. The use of encryption   can be regulated in certain regions, so check that it's used in conformance to local regulations.

**This paragraph feels more like _globalization_ - suggest either removing or using as an example for the i18n validation article, in the "Cultural awareness and market conventions" section** 

The ordering of names is another good example. The order in which surname and first name appear varies according to country and region. For instance, some Muslim countries and certain regions in India use a different name order than that used in English. People might have single names, multi-part names, or names that otherwise don't fit the first-last pattern.

2024-04-17 11:52 UTC, m-kauppinen commented
> Thanks for a great read, @m-kauppinen - I'm done with my comments. Note this was quite hard to review as the content was generally very good, but I struggled with the way things flowed within and across articles or how we ordered the different complementary validation activities - that's the bulk of comments, sorry that these are quite long. I also made some somewhat preferential tweaks based on my own preference on how to approach i18n testing. FYI @jowilco

Thanks for your detailed feedback, Bruno! I'll wait a bit to see what John has to say before starting to implement all this.

2024-05-03 13:02 UTC, m-kauppinen commented on globalization/testing/how-to-test.md
> +The second consists of culture-specific, language-specific, and country- or region-specific areas. Examples include configurable components such as region defaults and the default language, as well a
I deleted the last paragraph and instead added a 6th item in the list under "Cultural awareness and market conventions," as we cover the topic in more detail in another article.

2024-05-03 13:25 UTC, m-kauppinen commented on globalization/testing/how-to-test.md
> +## In-context review
I did that and deleted one heading to make the subsections of more equal "weight."

2024-05-03 13:48 UTC, m-kauppinen commented on globalization/testing/how-to-test.md
> +
I moved both sections to the other article and expanded the intro section in this one as you suggested.

2024-05-03 13:58 UTC, m-kauppinen commented on globalization/testing/when-to-test.md
> +This review phase becomes even more important if your localizability testing relies on pseudolocalization. It works well to find code, string handling, and layout problems in your app, but is less ef
I think we can remove it.

2024-05-03 14:06 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum total score of 80 is required.**
 
Select the total score link to review all feedback on clarity, consistency, tone, brand, terms, spelling, grammar, readability, and inclusive language. _You should fix all spelling errors regardless of your total score_. Fixing spelling errors helps maintain customer trust in overall content quality.

| Article | Total score<br>(Required: 80) | Words + phrases<br>(Brand, terms) | Correctness<br>(Spelling, grammar) | Clarity<br>(Readability) |
|---------|:--------------:|:--------------------:|:------:|:---------:|
| [:white_check_mark:](# "Successfully processed") [globalization/methodology/how-to-validate-internationalized-products.md](https://github.com/MicrosoftDocs/globalization/blob/5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35/globalization%2Fmethodology%2Fhow-to-validate-internationalized-products.md) | [87](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/935070f2-59ce-4b34-9037-bfd5ddc11a54) | 100 | 100 | 43 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/how-to-test-internationalized-products.md](https://github.com/MicrosoftDocs/globalization/blob/5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35/globalization%2Ftesting%2Fhow-to-test-internationalized-products.md) | [92](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4146d245-17a2-411a-8671-3f9b92d2a429) | 100 | 100 | 61 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/how-to-test.md](https://github.com/MicrosoftDocs/globalization/blob/5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35/globalization%2Ftesting%2Fhow-to-test.md) | [84](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/445d6f4d-70f6-4d50-87af-8bc530255d01) | 100 | 95 | 65 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/what-to-look-for-when-testing.md](https://github.com/MicrosoftDocs/globalization/blob/5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35/globalization%2Ftesting%2Fwhat-to-look-for-when-testing.md) | [93](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59b46604-cbb2-4b63-8826-504a628c38c0) | 100 | 89 | 87 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/when-to-test.md](https://github.com/MicrosoftDocs/globalization/blob/5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35/globalization%2Ftesting%2Fwhen-to-test.md) | [85](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2ab96c7-1274-4961-900a-c19e15f6fd8d) | 100 | 89 | 49 |
| [:white_check_mark:](# "Successfully processed") [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35/globalization%2Ftoc.yml) | [99](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/838e4cbd-7343-42ea-8d87-2895fa2eef7d) | 100 | 100 | 95 |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-05-03 15:07 UTC, brunolewin-msft commented
> @brunolewin-msft @jowilco I'm still pondering some of the higher-level organizational comments, but I just committed a bunch of smaller edits so you have something to look at.

Thanks for that,  @m-kauppinen, I will review that today. Also, let me know if it's easier to just have a quick call about any of this.

2024-05-03 22:09 UTC, brunolewin-msft commented
@m-kauppinen the changes in 5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35 look great. Thanks for that. Noe, it's just going to take me a bit of time to match them to comments & resolve!

2024-05-08 21:27 UTC, brunolewin-msft commented on globalization/methodology/how-to-validate-internationalized-products.md
> +Planning an international product release is an involved process. You need to consider legal requirements, banking and payments, product delivery, regional support, and the localization process. All
Change in 5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35 looks great, thank you

2024-05-08 21:29 UTC, brunolewin-msft commented on globalization/methodology/how-to-validate-internationalized-products.md
> +As you [internationalize](software-internationalization.md) your product, you should start validating support for worldwide users with localizability testing. You'll need to validate that:
Change in 5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35 looks great, thank you

2024-05-08 21:29 UTC, brunolewin-msft commented on globalization/methodology/how-to-validate-internationalized-products.md
> +Localization testing should ensure all the user interface text is displayed correctly following the conventions of each target language and culture. It should convey the same meaning as the source te
Change in 5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35 looks great, thank you.

2024-05-08 21:31 UTC, brunolewin-msft commented on globalization/testing/how-to-test-internationalized-products.md
> +Ensuring world-readiness has a wider scope and requires more planning than just testing your app after the UI strings have been translated. The QA team must partner with the development team and proj
Both change in 5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35 look great, thank you.

2024-05-08 21:31 UTC, brunolewin-msft commented on globalization/testing/what-to-look-for-when-testing.md
> +## Test data for localizability testing
Change in 5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35 looks great, thank you.

2024-05-08 21:38 UTC, brunolewin-msft commented on globalization/testing/what-to-look-for-when-testing.md
> +- Translations are correct: terminology, style, and meaning are accurately conveyed
Change in 5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35 looks great, thank you.

2024-05-08 21:40 UTC, brunolewin-msft commented on globalization/testing/when-to-test.md
> +However, bugs and other issues are often more apparent after the translations have been implemented. Localization is expensive, so it’s usually done after the code is complete and stable enough. Ther
5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35 looks good

2024-05-08 21:42 UTC, brunolewin-msft commented on globalization/testing/when-to-test.md
> +Once you pseudolocalize your app, [test its functionality](how-to-test.md). A pseudolocalized app should function exactly like its source language version. Besides detecting localizability bugs, pseu
Change looks good, thanks!

2024-05-08 21:43 UTC, brunolewin-msft commented on globalization/testing/when-to-test.md
> +As discussed previously, [pseudolocalization](#test-with-a-pseudolocalized-version-of-your-app) can be extremely helpful, but it can never catch all issues. If you start the actual localization with
5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35 looks great

2024-05-08 21:44 UTC, brunolewin-msft commented on globalization/testing/when-to-test.md
> +Every language is different, and localizing just one or two can't reveal every possible issue. But combined with the above phases, it gives you a solid foundation for localizing your complete languag
5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35 looks great

2024-05-08 21:45 UTC, brunolewin-msft commented on globalization/testing/how-to-test.md
> +[Pseudolocalization](../methodology/pseudolocalization.md) is a powerful tool for uncovering many issues during localizability testing. When you [test for localizability](when-to-test.md) before you
5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35 looks good

2024-05-08 21:46 UTC, brunolewin-msft commented on globalization/testing/how-to-test.md
> +This article discusses the methods and tools for testing your localized products. For information about localizability testing, that is, what you should validate before starting localization, see [Wh
5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35 looks good

2024-05-08 21:47 UTC, brunolewin-msft commented on globalization/testing/how-to-test.md
> +Localization testing checks how well your product is translated into a particular target language. Localization testing is an extension of [localizability testing](when-to-test.md), where the functio
5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35 looks great

2024-05-08 21:49 UTC, brunolewin-msft commented on globalization/testing/how-to-test.md
> +
Thanks for that, looks good

2024-05-08 21:52 UTC, brunolewin-msft commented on globalization/testing/how-to-test.md
> +### Localization testing for UI and language
Changes in 5cb98ed25456d1cf1709d3fb2cfc3c86f3901c35 looks great, thank you.

2024-05-15 13:59 UTC, m-kauppinen commented on globalization/testing/what-to-look-for-when-testing.md
> +### Displaying user data
I moved the items into "Technical implementation" and then renamed it "Text support."

2024-05-16 13:05 UTC, m-kauppinen commented on globalization/testing/how-to-test.md
> +
@brunolewin-msft I think I have now implemented your other comments for this article. I'm a bit unsure what should/could be moved elsewhere, except the section titled Localization, as this article is supposed to be about pre-localization stuff? I committed a new version so you can see how it looks now.

2024-05-16 13:07 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum total score of 80 is required.**
 
Select the total score link to review all feedback on clarity, consistency, tone, brand, terms, spelling, grammar, readability, and inclusive language. _You should fix all spelling errors regardless of your total score_. Fixing spelling errors helps maintain customer trust in overall content quality.

| Article | Total score<br>(Required: 80) | Words + phrases<br>(Brand, terms) | Correctness<br>(Spelling, grammar) | Clarity<br>(Readability) |
|---------|:--------------:|:--------------------:|:------:|:---------:|
| [:white_check_mark:](# "Successfully processed") [globalization/methodology/how-to-validate-internationalized-products.md](https://github.com/MicrosoftDocs/globalization/blob/ec545047d133119a3357e2b1b7cbc259e19a41b0/globalization%2Fmethodology%2Fhow-to-validate-internationalized-products.md) | [87](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/219e7bb0-5687-4721-b314-1200df40f92f) | 100 | 100 | 43 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/how-to-test-internationalized-products.md](https://github.com/MicrosoftDocs/globalization/blob/ec545047d133119a3357e2b1b7cbc259e19a41b0/globalization%2Ftesting%2Fhow-to-test-internationalized-products.md) | [92](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af5bc4d1-1614-47ae-8824-e25e37f4e3a3) | 100 | 100 | 61 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/how-to-test.md](https://github.com/MicrosoftDocs/globalization/blob/ec545047d133119a3357e2b1b7cbc259e19a41b0/globalization%2Ftesting%2Fhow-to-test.md) | [84](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8690979-4df7-4d2f-8b35-0ddbe939c6f8) | 100 | 95 | 65 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/what-to-look-for-when-testing.md](https://github.com/MicrosoftDocs/globalization/blob/ec545047d133119a3357e2b1b7cbc259e19a41b0/globalization%2Ftesting%2Fwhat-to-look-for-when-testing.md) | [87](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31df883c-edab-4ddb-89f0-3ea08b89124b) | 100 | 90 | 66 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/when-to-test.md](https://github.com/MicrosoftDocs/globalization/blob/ec545047d133119a3357e2b1b7cbc259e19a41b0/globalization%2Ftesting%2Fwhen-to-test.md) | [85](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23311607-baa5-4481-9555-62ea75d16903) | 100 | 89 | 49 |
| [:white_check_mark:](# "Successfully processed") [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/ec545047d133119a3357e2b1b7cbc259e19a41b0/globalization%2Ftoc.yml) | [99](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b86cec47-7e97-4e35-8248-f071c66aa8ea) | 100 | 100 | 95 |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-05-17 13:18 UTC, m-kauppinen commented on globalization/testing/how-to-test.md
> +Localization testing should focus on several general areas.
I added the breakdown and linked the subsections. Do we have a good article for functional testing that we could link to?

2024-05-17 14:05 UTC, m-kauppinen commented on globalization/testing/when-to-test.md
> +You should ensure the terminology used in your app’s user interface and support documentation is clear, consistent, and unambiguous. Translators find it harder to do a good job if the UI and the docu
I added a sentence to the end of the paragraph to hopefully illustrate that.

2024-05-17 14:07 UTC, m-kauppinen commented on globalization/testing/when-to-test.md
> +
I split the list in two as you suggested.

2024-05-17 14:09 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum total score of 80 is required.**
 
Select the total score link to review all feedback on clarity, consistency, tone, brand, terms, spelling, grammar, readability, and inclusive language. _You should fix all spelling errors regardless of your total score_. Fixing spelling errors helps maintain customer trust in overall content quality.

| Article | Total score<br>(Required: 80) | Words + phrases<br>(Brand, terms) | Correctness<br>(Spelling, grammar) | Clarity<br>(Readability) |
|---------|:--------------:|:--------------------:|:------:|:---------:|
| [:white_check_mark:](# "Successfully processed") [globalization/methodology/how-to-validate-internationalized-products.md](https://github.com/MicrosoftDocs/globalization/blob/621e68bd821c8e2d21505d36d88a71a1306f4c0d/globalization%2Fmethodology%2Fhow-to-validate-internationalized-products.md) | [87](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ac75fb9-3c1c-45f8-8629-41abdca62c4c) | 100 | 100 | 43 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/how-to-test-internationalized-products.md](https://github.com/MicrosoftDocs/globalization/blob/621e68bd821c8e2d21505d36d88a71a1306f4c0d/globalization%2Ftesting%2Fhow-to-test-internationalized-products.md) | [92](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/873e4512-7e2a-47f5-bd9e-87fffd3bb5af) | 100 | 100 | 61 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/how-to-test.md](https://github.com/MicrosoftDocs/globalization/blob/621e68bd821c8e2d21505d36d88a71a1306f4c0d/globalization%2Ftesting%2Fhow-to-test.md) | [84](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b965ce25-97fc-43c6-ab1b-9e576ddf62da) | 100 | 95 | 64 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/what-to-look-for-when-testing.md](https://github.com/MicrosoftDocs/globalization/blob/621e68bd821c8e2d21505d36d88a71a1306f4c0d/globalization%2Ftesting%2Fwhat-to-look-for-when-testing.md) | [87](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/134804ac-56d7-4277-aef3-928fd117a935) | 100 | 90 | 66 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/when-to-test.md](https://github.com/MicrosoftDocs/globalization/blob/621e68bd821c8e2d21505d36d88a71a1306f4c0d/globalization%2Ftesting%2Fwhen-to-test.md) | [85](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc6563d2-f1fa-4618-a583-293e2db6927a) | 100 | 89 | 50 |
| [:white_check_mark:](# "Successfully processed") [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/621e68bd821c8e2d21505d36d88a71a1306f4c0d/globalization%2Ftoc.yml) | [99](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f2cd123-c1da-4e84-9545-31d12cc3f4b0) | 100 | 100 | 95 |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-06-04 15:28 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum total score of 80 is required.**
 
Select the total score link to review all feedback on clarity, consistency, tone, brand, terms, spelling, grammar, readability, and inclusive language. _You should fix all spelling errors regardless of your total score_. Fixing spelling errors helps maintain customer trust in overall content quality.

| Article | Total score<br>(Required: 80) | Words + phrases<br>(Brand, terms) | Correctness<br>(Spelling, grammar) | Clarity<br>(Readability) |
|---------|:--------------:|:--------------------:|:------:|:---------:|
| [:white_check_mark:](# "Successfully processed") [globalization/methodology/how-to-validate-internationalized-products.md](https://github.com/MicrosoftDocs/globalization/blob/f075f7ea741aa01a95b9030eb1a790655f140e99/globalization%2Fmethodology%2Fhow-to-validate-internationalized-products.md) | [88](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25e62d2f-a644-48fb-a5eb-6b0673e990c9) | 100 | 100 | 43 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/how-to-test-internationalized-products.md](https://github.com/MicrosoftDocs/globalization/blob/f075f7ea741aa01a95b9030eb1a790655f140e99/globalization%2Ftesting%2Fhow-to-test-internationalized-products.md) | [89](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eadd3f5f-2b0f-4ec6-92a6-1bd522f9d929) | 100 | 94 | 60 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/how-to-test.md](https://github.com/MicrosoftDocs/globalization/blob/f075f7ea741aa01a95b9030eb1a790655f140e99/globalization%2Ftesting%2Fhow-to-test.md) | [84](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32d71b8d-031b-4164-8521-9a3bed90d397) | 100 | 95 | 66 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/what-to-look-for-when-testing.md](https://github.com/MicrosoftDocs/globalization/blob/f075f7ea741aa01a95b9030eb1a790655f140e99/globalization%2Ftesting%2Fwhat-to-look-for-when-testing.md) | [85](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fabd8dea-0643-4c64-906a-97983cfe7c4c) | 100 | 88 | 56 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/when-to-test.md](https://github.com/MicrosoftDocs/globalization/blob/f075f7ea741aa01a95b9030eb1a790655f140e99/globalization%2Ftesting%2Fwhen-to-test.md) | [87](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a63e5328-960c-4b01-bf90-67a179e7f62f) | 100 | 79 | 56 |
| [:white_check_mark:](# "Successfully processed") [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/f075f7ea741aa01a95b9030eb1a790655f140e99/globalization%2Ftoc.yml) | [99](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/863267bb-4e78-43b1-8199-c131c72f887e) | 100 | 100 | 95 |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-06-04 15:34 UTC, m-kauppinen commented
@brunolewin-msft @jowilco I just committed a set of changes trying to implement what we talked about in the meeting. I moved most of When... to How..., retitled articles, got rid of "localizability" in favor of "internationalization, and so on. I did not update the TOC yet in case you want to rename the articles in some other way.

2024-06-04 15:36 UTC, brunolewin-msft commented
Thanks, let me try to review this today.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: m-kauppinen ***@***.***>
Sent: Tuesday, June 4, 2024 8:35:01 AM
To: MicrosoftDocs/globalization ***@***.***>
Cc: Bruno Lewin (Centific Technologies Inc) ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/globalization] Validation articles (PR #301)


@brunolewin-msft<https://github.com/brunolewin-msft> @jowilco<https://github.com/jowilco> I just committed a set of changes trying to implement what we talked about in the meeting. I moved most of When... to How..., retitled articles, got rid of "localizability" in favor of "internationalization, and so on. I did not update the TOC yet in case you want to rename the articles in some other way.

—
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/globalization/pull/301#issuecomment-2147839293>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AEKVIQBPUIMFOM5OC6VKXM3ZFXNCLAVCNFSM6AAAAABGANT2LGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNBXHAZTSMRZGM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-06-06 01:06 UTC, brunolewin-msft submitted a review, later dismissed
Thanks a lot for the latest changes - really like how things flow now.

2024-06-07 08:13 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum total score of 80 is required.**
 
Select the total score link to review all feedback on clarity, consistency, tone, brand, terms, spelling, grammar, readability, and inclusive language. _You should fix all spelling errors regardless of your total score_. Fixing spelling errors helps maintain customer trust in overall content quality.

| Article | Total score<br>(Required: 80) | Words + phrases<br>(Brand, terms) | Correctness<br>(Spelling, grammar) | Clarity<br>(Readability) |
|---------|:--------------:|:--------------------:|:------:|:---------:|
| [:white_check_mark:](# "Successfully processed") [globalization/methodology/how-to-validate-internationalized-products.md](https://github.com/MicrosoftDocs/globalization/blob/f9f27e6d627e2b28b4fbfb1ff38fffbe8371bc04/globalization%2Fmethodology%2Fhow-to-validate-internationalized-products.md) | [88](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2bfbcd6a-f414-4e88-a7e6-70343449fa70) | 100 | 100 | 43 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/how-to-test-internationalized-products.md](https://github.com/MicrosoftDocs/globalization/blob/f9f27e6d627e2b28b4fbfb1ff38fffbe8371bc04/globalization%2Ftesting%2Fhow-to-test-internationalized-products.md) | [89](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/544927df-5b16-44b5-b49e-a5387e270320) | 100 | 94 | 60 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/how-to-test.md](https://github.com/MicrosoftDocs/globalization/blob/f9f27e6d627e2b28b4fbfb1ff38fffbe8371bc04/globalization%2Ftesting%2Fhow-to-test.md) | [84](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c18eb7f8-71d6-4251-b553-da58c3197182) | 100 | 95 | 66 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/what-to-look-for-when-testing.md](https://github.com/MicrosoftDocs/globalization/blob/f9f27e6d627e2b28b4fbfb1ff38fffbe8371bc04/globalization%2Ftesting%2Fwhat-to-look-for-when-testing.md) | [85](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e025a71-7538-4c7b-b6aa-9de552e89f20) | 100 | 88 | 56 |
| [:white_check_mark:](# "Successfully processed") [globalization/testing/when-to-test.md](https://github.com/MicrosoftDocs/globalization/blob/f9f27e6d627e2b28b4fbfb1ff38fffbe8371bc04/globalization%2Ftesting%2Fwhen-to-test.md) | [87](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bd80918-6c0a-41a9-aaf1-5e0c0960ec3c) | 100 | 79 | 56 |
| [:white_check_mark:](# "Successfully processed") [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/f9f27e6d627e2b28b4fbfb1ff38fffbe8371bc04/globalization%2Ftoc.yml) | [99](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/328ca77f-5646-4ca3-b5ce-17320a36c085) | 100 | 100 | 95 |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-06-07 15:01 UTC, jowilco approved these changes

2024-06-07 15:27 UTC, merged