99379 ai
MicrosoftDocs/globalization pull request #318
Opened 2024-08-15 16:09 UTC by jowilco

2024-08-15 16:09 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum total score of 80 is required.**
 
Select the total score link to review all feedback on clarity, consistency, tone, brand, terms, spelling, grammar, readability, and inclusive language. _You should fix all spelling errors regardless of your total score_. Fixing spelling errors helps maintain customer trust in overall content quality.

| Article | Total score<br>(Required: 80) | Words + phrases<br>(Brand, terms) | Correctness<br>(Spelling, grammar) | Clarity<br>(Readability) |
|---------|:--------------:|:--------------------:|:------:|:---------:|
| [:white_check_mark:](# "Successfully processed") [globalization/localization/ai/ai-and-llms-for-translation.md](https://github.com/MicrosoftDocs/globalization/blob/d09624db9fa6be241305e82baf4fccda054ecb4b/globalization%2Flocalization%2Fai%2Fai-and-llms-for-translation.md) | [90](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c1234bf-f3cf-4016-88eb-4e2fb9b1b504) | 100 | 100 | 69 |
| [:white_check_mark:](# "Successfully processed") [globalization/localization/ai/ai-and-localization.md](https://github.com/MicrosoftDocs/globalization/blob/d09624db9fa6be241305e82baf4fccda054ecb4b/globalization%2Flocalization%2Fai%2Fai-and-localization.md) | [90](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f9be742-cdc0-4f80-a048-5afe1fa0299d) | 100 | 89 | 62 |
| [:white_check_mark:](# "Successfully processed") [globalization/localization/ai/localizing-ai-based-features.md](https://github.com/MicrosoftDocs/globalization/blob/d09624db9fa6be241305e82baf4fccda054ecb4b/globalization%2Flocalization%2Fai%2Flocalizing-ai-based-features.md) | [88](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f43ebfab-a941-4fd3-81e5-abc08bd3ec30) | 100 | 100 | 58 |
| [:white_check_mark:](# "Successfully processed") [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/d09624db9fa6be241305e82baf4fccda054ecb4b/globalization%2Ftoc.yml) | [95](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89fcd982-ff89-4c88-bc90-a97330a58d15) | 100 | 84 | 95 |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-08-15 17:20 UTC, brunolewin-msft commented on globalization/localization/ai/ai-and-localization.md
> +description: Use AI for global strategy by ensuring responsible practices and inclusive design to avoid biases, enhance user experience, and drive product success worldwide.
Great intro article. I really like how it succinctly explains the 2 key int'l aspects, introduces RAI and ties to int'l considerations. The current title and description don't feel as good: title only mentions _localization_ and description misses the non-RAI aspects so they feel a bit disconnected and do the article justice.

2024-08-15 17:29 UTC, brunolewin-msft commented on globalization/localization/ai/ai-and-localization.md
> +description: Use AI for global strategy by ensuring responsible practices and inclusive design to avoid biases, enhance user experience, and drive product success worldwide.
Possibly something along the lines of: "_Use AI for translation and ensure that AI-based features meet global expectation to drive product success worldwide_" (inspired from the other two articles)

2024-08-15 17:40 UTC, brunolewin-msft commented on globalization/localization/ai/ai-and-llms-for-translation.md
> +With recent advances in large language models (LLMs), many localizers are considering whether to use AI instead of existing machine translation (MT) systems or even as a replacement for human transla
Good point, but some style comments/suggestions:
- many **localizers** --> remove localizers. They might be the last ones to want this and other functions tend to be the ones doing the _considering_.
- replace human **translators** (HT) --> human **translation** (HT) - this is a touchy subject, so better call out that this is about _changing a process_, not replacing people (whose role might evolve rather than just be eliminated)
- “**high-resource**” languages --> jargon that not all will understand, either use plain language or just use "some languages" if you want to keep concise.

2024-08-15 17:58 UTC, brunolewin-msft commented on globalization/localization/ai/ai-and-llms-for-translation.md
> +### Large language models and globalization
This sub-section has good information but a lot of it feels out of scope under "Artificial intelligence and translation technology". It feels like the point that's implicitly made in this sub-section as well as in **Using LLMs for localization tasks other than translation** is that LLM are able to directly provide output in multiple languages and that might remove the need for translation - it could be easier on the reader to explain that explicitly in its own section and move the relevant pieces under that.

2024-08-15 19:14 UTC, joeyobr reviewed
John, I'll send you a Word doc with my edits.

2024-08-15 19:51 UTC, brunolewin-msft commented on globalization/localization/ai/ai-and-llms-for-translation.md
> +Due to their wide applicability for language processing tasks, consider using LLMs for other tasks in your localization workflow. For example,
If we encourage readers to use LLM for these tasks, it might be could to remind to have a have a reminder that it's not trivial how to do this **well and responsibly**. A more neutral option for this paragraph could to be to say that below are areas that the industry is exploring rather than suggest that the reader try them.

2024-08-15 21:37 UTC, agustd requested changes

2024-08-15 21:45 UTC, jowilco commented on globalization/localization/ai/localizing-ai-based-features.md
> +## LLM prompt engineering and testing the output
@jowilco - Use i18n prompt rules from Khipu

2024-08-15 22:36 UTC, brunolewin-msft commented on globalization/localization/ai/localizing-ai-based-features.md
> +### Cross-border data flow and AI laws
Minor: consider merging the regulatory considerations currently under in "Region availability" into **Cross-border data flow and AI laws** so all the regulatory bits are together.

2024-08-15 22:47 UTC, brunolewin-msft commented on globalization/localization/ai/localizing-ai-based-features.md
> +## Considerations for effective LLM prompts
The title (effective LLM prompts) does not really match the content of this section - consider breaking out the various regulatory/deployment points unrelated to prompt engineering into their own "level 2" section - see also my next comment,

2024-08-15 22:50 UTC, brunolewin-msft commented on globalization/localization/ai/localizing-ai-based-features.md
> +It's essential to ensure that the LLM's outputs align with business goals and user expectations. Consider an LLM generating marketing emails. Without evaluation, these emails might come across as too
Might be good to also mention evaluating basic linguistic quality in the languages being considered.

2024-08-16 16:45 UTC, jowilco commented on globalization/localization/ai/ai-and-llms-for-translation.md
> +### Large language models and globalization
This section introduces terms and concepts; however, I moved it outside of the AI and translation technology section

2024-08-16 18:04 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum total score of 80 is required.**
 
Select the total score link to review all feedback on clarity, consistency, tone, brand, terms, spelling, grammar, readability, and inclusive language. _You should fix all spelling errors regardless of your total score_. Fixing spelling errors helps maintain customer trust in overall content quality.

| Article | Total score<br>(Required: 80) | Words + phrases<br>(Brand, terms) | Correctness<br>(Spelling, grammar) | Clarity<br>(Readability) |
|---------|:--------------:|:--------------------:|:------:|:---------:|
| [:white_check_mark:](# "Successfully processed") [globalization/localization/ai/ai-and-llms-for-translation.md](https://github.com/MicrosoftDocs/globalization/blob/959c0a7c0e9132489a35e7ad956b8c81af77f67f/globalization%2Flocalization%2Fai%2Fai-and-llms-for-translation.md) | [85](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/efbd9593-3ae4-4dcf-8b56-d84b7ef306ce) | 95 | 90 | 66 |
| [:white_check_mark:](# "Successfully processed") [globalization/localization/ai/ai-and-localization.md](https://github.com/MicrosoftDocs/globalization/blob/959c0a7c0e9132489a35e7ad956b8c81af77f67f/globalization%2Flocalization%2Fai%2Fai-and-localization.md) | [90](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dcd04a1e-5a0d-4288-a3b5-44b61eb40581) | 100 | 89 | 62 |
| [:white_check_mark:](# "Successfully processed") [globalization/localization/ai/localizing-ai-based-features.md](https://github.com/MicrosoftDocs/globalization/blob/959c0a7c0e9132489a35e7ad956b8c81af77f67f/globalization%2Flocalization%2Fai%2Flocalizing-ai-based-features.md) | [91](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6b7a514-1df7-411e-809d-4b5d5ad32e2f) | 100 | 100 | 69 |
| [:white_check_mark:](# "Successfully processed") [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/959c0a7c0e9132489a35e7ad956b8c81af77f67f/globalization%2Ftoc.yml) | [95](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce7fcf30-58c4-4deb-9ed3-cb5bd3b5975d) | 100 | 84 | 95 |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-08-16 18:07 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum total score of 80 is required.**
 
Select the total score link to review all feedback on clarity, consistency, tone, brand, terms, spelling, grammar, readability, and inclusive language. _You should fix all spelling errors regardless of your total score_. Fixing spelling errors helps maintain customer trust in overall content quality.

| Article | Total score<br>(Required: 80) | Words + phrases<br>(Brand, terms) | Correctness<br>(Spelling, grammar) | Clarity<br>(Readability) |
|---------|:--------------:|:--------------------:|:------:|:---------:|
| [:white_check_mark:](# "Successfully processed") [globalization/localization/ai/ai-and-llms-for-translation.md](https://github.com/MicrosoftDocs/globalization/blob/09e5d6db6418a7744754c51dea78374500fa65c1/globalization%2Flocalization%2Fai%2Fai-and-llms-for-translation.md) | [85](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67e02336-10c2-48fd-b3b9-e8c6d9066d1b) | 95 | 90 | 66 |
| [:white_check_mark:](# "Successfully processed") [globalization/localization/ai/ai-and-localization.md](https://github.com/MicrosoftDocs/globalization/blob/09e5d6db6418a7744754c51dea78374500fa65c1/globalization%2Flocalization%2Fai%2Fai-and-localization.md) | [90](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6db937f4-4659-4626-b1ea-f9adf67d52f0) | 100 | 89 | 62 |
| [:white_check_mark:](# "Successfully processed") [globalization/localization/ai/localizing-ai-based-features.md](https://github.com/MicrosoftDocs/globalization/blob/09e5d6db6418a7744754c51dea78374500fa65c1/globalization%2Flocalization%2Fai%2Flocalizing-ai-based-features.md) | [91](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a26df48-229e-4a0b-90fe-09014cdbd1a0) | 100 | 100 | 69 |
| [:white_check_mark:](# "Successfully processed") [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/09e5d6db6418a7744754c51dea78374500fa65c1/globalization%2Ftoc.yml) | [95](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34d2b184-fe5f-40c3-9f96-720b94f3fdc1) | 100 | 84 | 95 |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-08-16 18:38 UTC, brunolewin-msft commented on globalization/localization/ai/ai-and-llms-for-translation.md
> +Cost-wise, some of the latest AI models are slightly cost-effective than their predecessors. However, the total cost of ownership, which includes both the operational and personnel costs, must be tak
slightly **more** cost-effective?

2024-08-16 18:42 UTC, brunolewin-msft commented on globalization/localization/ai/ai-and-llms-for-translation.md
> +- the system’s performance
maybe add impact on people/processes to that list?

2024-08-16 18:45 UTC, joeyobr approved these changes

2024-08-16 18:49 UTC, agustd approved these changes

2024-08-16 19:30 UTC, acrolinxatmsft1 commented
## Acrolinx Scorecards

**A minimum total score of 80 is required.**
 
Select the total score link to review all feedback on clarity, consistency, tone, brand, terms, spelling, grammar, readability, and inclusive language. _You should fix all spelling errors regardless of your total score_. Fixing spelling errors helps maintain customer trust in overall content quality.

| Article | Total score<br>(Required: 80) | Words + phrases<br>(Brand, terms) | Correctness<br>(Spelling, grammar) | Clarity<br>(Readability) |
|---------|:--------------:|:--------------------:|:------:|:---------:|
| [:white_check_mark:](# "Successfully processed") [globalization/localization/ai/ai-and-llms-for-translation.md](https://github.com/MicrosoftDocs/globalization/blob/e15f95d08e081e601e65da29e77e956af7bc8d65/globalization%2Flocalization%2Fai%2Fai-and-llms-for-translation.md) | [86](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee9b6266-c710-4cdf-a0c0-e886c9aa196c) | 95 | 95 | 66 |
| [:white_check_mark:](# "Successfully processed") [globalization/localization/ai/ai-and-localization.md](https://github.com/MicrosoftDocs/globalization/blob/e15f95d08e081e601e65da29e77e956af7bc8d65/globalization%2Flocalization%2Fai%2Fai-and-localization.md) | [90](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e04e29c-d03b-4608-a5da-4d2ac1b1ef4d) | 100 | 89 | 62 |
| [:white_check_mark:](# "Successfully processed") [globalization/localization/ai/localizing-ai-based-features.md](https://github.com/MicrosoftDocs/globalization/blob/e15f95d08e081e601e65da29e77e956af7bc8d65/globalization%2Flocalization%2Fai%2Flocalizing-ai-based-features.md) | [91](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d22a6220-812e-40f5-8190-49fc1b109484) | 100 | 100 | 69 |
| [:white_check_mark:](# "Successfully processed") [globalization/toc.yml](https://github.com/MicrosoftDocs/globalization/blob/e15f95d08e081e601e65da29e77e956af7bc8d65/globalization%2Ftoc.yml) | [95](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7dcb7220-4985-43dc-ac4b-b7f8ca66ce44) | 100 | 84 | 95 |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

2024-08-16 19:37 UTC, merged